package codegen

// C++ emitter. Each proto file's components are emitted into ONE header-only
// wiring file (templates must live in headers) named <protofile>_angzarr.h: a
// public abstract <Component>Handler (the strict seam, pure-virtual methods), an
// inline New<Component>Dispatch factory, and an inline Register<Component> per
// component. Like the C# emitter, the dispatch surfaces are generic in the
// component state message (templates), so the generated wiring is cast-free; the
// single erasing cast lives in the binding's invoker adapters. Type references
// are fully qualified: framework messages under io::angzarr::v1, runtime types
// under angzarr::router, domain messages from the proto package (dots→"::").
// Google.Protobuf C++ messages are mutable and default-constructible, so there
// is no state factory — the binding default-constructs TState.

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	cppRouter       = "angzarr::router::Router"
	cppAggDispatch  = "angzarr::router::AggregateDispatch"
	cppSagaDispatch = "angzarr::router::SagaDispatch"
	cppProjDispatch = "angzarr::router::ProjectorDispatch"
	cppPmDispatch   = "angzarr::router::ProcessManagerDispatch"
	cppRebuilder    = "angzarr::router::Rebuilder"
	cppCctx         = "angzarr::router::CommandContext"
	cppDestinations = "angzarr::router::Destinations"
	cppPack         = "angzarr::router::Pack"
	cppCoded        = "angzarr::router::CodedError"
	cppSagaEmission = "angzarr::router::SagaEmission"
	cppPmRejection  = "angzarr::router::PmRejection"
	cppAny          = "google::protobuf::Any"
	cppEventBook    = "io::angzarr::v1::EventBook"
	cppEventPage    = "io::angzarr::v1::EventPage"
	cppBusinessResp = "io::angzarr::v1::BusinessResponse"
	cppNotification = "io::angzarr::v1::Notification"
	cppRejNotif     = "io::angzarr::v1::RejectionNotification"
	cppProjection   = "io::angzarr::v1::Projection"
	cppPmResponse   = "io::angzarr::v1::ProcessManagerHandleResponse"
	cppVector       = "std::vector"
)

type cppEmitter struct{}

func (cppEmitter) Lang() string { return "cpp" }

func (cppEmitter) WiringPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr.h")
}

func (cppEmitter) ScaffoldPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr_handler.h")
}

func (e cppEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// <auto-generated>")
	g.P("// Code generated by angzarr codegen cpp. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("#pragma once")
	g.P()
	g.P(`#include "angzarr/router/router.h"`)
	for _, inc := range e.includes(file, []*Service{s}) {
		g.P(`#include "`, inc, `"`)
	}
	g.P()
	g.P("namespace ", cppNamespace(file), " {")
	g.P()
	var err error
	switch s.Component.Kind {
	case KindAggregate:
		err = e.emitAggregate(g, s)
	case KindSaga:
		err = e.emitSaga(g, s)
	case KindProjector:
		err = e.emitProjector(g, s)
	case KindProcessManager:
		err = e.emitPM(g, s)
	default:
		err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
	if err != nil {
		return err
	}
	g.P("}  // namespace ", cppNamespace(file))
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e cppEmitter) emitInterface(g *protogen.GeneratedFile, s *Service, doc string) {
	g.P("// The strict business seam for the ", doc, ". Every declared")
	g.P("// command/event must be implemented — a missing handler is a compile error.")
	g.P("class ", s.GoName, "Handler {")
	g.P(" public:")
	g.P("  virtual ~", s.GoName, "Handler() = default;")
	for _, m := range e.methods(s) {
		g.P("  virtual ", m.results, " ", m.name, "(", m.params, ") = 0;")
	}
	g.P("};")
	g.P()
}

type cppMethod struct {
	name    string
	params  string
	results string
}

func (e cppEmitter) methods(s *Service) []cppMethod {
	switch s.Component.Kind {
	case KindAggregate:
		return e.aggregateMethods(s)
	case KindSaga:
		return e.sagaMethods(s)
	case KindProjector:
		return e.projectorMethods(s)
	case KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e cppEmitter) aggregateMethods(s *Service) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		results := cppEventBook
		if h.TypedEmit() {
			results = cppVector + "<" + cppType(h.Emits[0]) + ">"
		}
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& cmd, " + state + "& state, const " + cppCctx + "& cctx",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, cppMethod{
			name:    a.MethodName,
			params:  state + "& state, const " + cppType(a.Message) + "& ev",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, cppMethod{
			name:    r.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppRejNotif + "& rejection, " + state + "& state, const " + cppCctx + "& cctx",
			results: cppBusinessResp,
		})
	}
	return out
}

func (e cppEmitter) sagaMethods(s *Service) []cppMethod {
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& ev, const " + cppDestinations + "& dests",
			results: cppSagaEmission,
		})
	}
	for _, r := range s.Rejections {
		out = append(out, cppMethod{
			name:    r.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppRejNotif + "& rejection",
			results: cppVector + "<" + cppEventBook + ">",
		})
	}
	return out
}

func (e cppEmitter) projectorMethods(s *Service) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  state + "& projection, const " + cppType(h.Message) + "& ev",
			results: "void",
		})
	}
	out = append(out, cppMethod{
		name:    "Finish",
		params:  state + "& projection, const " + cppEventBook + "& events",
		results: cppProjection,
	})
	return out
}

func (e cppEmitter) pmMethods(s *Service) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& ev, " + state + "& state, const " + cppDestinations + "& dests",
			results: cppPmResponse,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, cppMethod{
			name:    a.MethodName,
			params:  state + "& state, const " + cppType(a.Message) + "& ev",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, cppMethod{
			name:    r.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppRejNotif + "& rejection, " + state + "& state",
			results: cppPmRejection,
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e cppEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" aggregate")
	state := cppType(s.State)
	disp := cppGeneric(cppAggDispatch, state)
	g.P("// Populates the aggregate table from the proto declaration.")
	g.P("inline ", disp, " New", s.GoName, "Dispatch(", s.GoName, "Handler& h) {")
	g.P("  ", cppGeneric(cppRebuilder, state), " rebuilder;")
	g.P("  rebuilder.WithSnapshot([](", state, "& state, const ", cppAny, "& payload) {")
	g.P("    ", cppCoded, "::Merge(state, payload);")
	g.P("  });")
	emitCppAppliers(g, s, state)
	g.P("  ", disp, " dispatch(", cppQuote(s.GoName), ", ", cppQuote(s.Component.InputDomain), ", std::move(rebuilder));")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnCommand(", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& cmdAny, ", state, "& state, const ", cppCctx, "& cctx) -> ", cppEventBook, " {")
		g.P("    auto cmd = ", cppParse(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("    auto events = h.", h.MethodName, "(cmd, state, cctx);")
			g.P("    ", cppEventBook, " book;")
			g.P("    for (const auto& ev : events) {")
			g.P("      *book.add_pages()->mutable_event() = ", cppPack, "::Wrap(ev);")
			g.P("    }")
			g.P("    return book;")
		} else {
			g.P("    return h.", h.MethodName, "(cmd, state, cctx);")
		}
		g.P("  });")
	}
	for _, r := range s.Rejections {
		g.P("  dispatch.OnRejected(", cppQuote(r.Command), ", [&h](const ", cppNotification, "& n, const ", cppRejNotif, "& rejection, ", state, "& state, const ", cppCctx, "& cctx) {")
		g.P("    return h.", r.MethodName, "(n, rejection, state, cctx);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterAggregate")
	return nil
}

func (e cppEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" saga")
	g.P("// Populates the saga table from the proto declaration.")
	g.P("inline ", cppSagaDispatch, " New", s.GoName, "Dispatch(", s.GoName, "Handler& h) {")
	g.P("  ", cppSagaDispatch, " dispatch(", cppQuote(s.GoName), ", ", cppQuote(s.Component.InputDomain), ", {", cppQuote(s.Component.OutputDomain), "});")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEvent(", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& eventAny, const ", cppDestinations, "& dests) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    return h.", h.MethodName, "(ev, dests);")
		g.P("  });")
	}
	for _, r := range s.Rejections {
		g.P("  dispatch.OnRejected(", cppQuote(r.Command), ", [&h](const ", cppNotification, "& n, const ", cppRejNotif, "& rejection) {")
		g.P("    return h.", r.MethodName, "(n, rejection);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterSaga")
	return nil
}

func (e cppEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" projector")
	state := cppType(s.State)
	disp := cppGeneric(cppProjDispatch, state)
	g.P("// Populates the projector table from the proto declaration.")
	g.P("inline ", disp, " New", s.GoName, "Dispatch(", s.GoName, "Handler& h) {")
	g.P("  ", disp, " dispatch(", cppQuote(s.GoName), ");")
	g.P("  dispatch.ForDomains({", cppQuote(s.Component.InputDomain), "});")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEvent(", cppQuote(fqName(h.Message)), ", [&h](", state, "& projection, const ", cppAny, "& eventAny) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    h.", h.MethodName, "(projection, ev);")
		g.P("  });")
	}
	g.P("  dispatch.Finish([&h](", state, "& projection, const ", cppEventBook, "& events) {")
	g.P("    return h.Finish(projection, events);")
	g.P("  });")
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterProjector")
	return nil
}

func (e cppEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" process manager")
	state := cppType(s.State)
	disp := cppGeneric(cppPmDispatch, state)
	g.P("// Populates the PM table from the proto declaration.")
	g.P("inline ", disp, " New", s.GoName, "Dispatch(", s.GoName, "Handler& h) {")
	g.P("  ", cppGeneric(cppRebuilder, state), " rebuilder;")
	g.P("  rebuilder.WithSnapshot([](", state, "& state, const ", cppAny, "& payload) {")
	g.P("    ", cppCoded, "::Merge(state, payload);")
	g.P("  });")
	emitCppAppliers(g, s, state)
	g.P("  ", disp, " dispatch(", cppQuote(s.GoName), ", ", cppQuote(s.Component.OutputDomain), ", std::move(rebuilder));")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEvent(", cppQuote(h.SourceDomain), ", ", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& eventAny, ", state, "& state, const ", cppDestinations, "& dests) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    return h.", h.MethodName, "(ev, state, dests);")
		g.P("  });")
	}
	for _, r := range s.Rejections {
		g.P("  dispatch.OnRejected(", cppQuote(r.Command), ", [&h](const ", cppNotification, "& n, const ", cppRejNotif, "& rejection, ", state, "& state) {")
		g.P("    return h.", r.MethodName, "(n, rejection, state);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterProcessManager")
	return nil
}

// emitCppAppliers registers each event applier on the rebuilder. Identical for
// aggregates and process managers (both rebuild their own state).
func emitCppAppliers(g *protogen.GeneratedFile, s *Service, state string) {
	for _, a := range s.Appliers {
		g.P("  rebuilder.Apply(", cppQuote(fqName(a.Message)), ", [&h](", state, "& state, const ", cppAny, "& payload) {")
		g.P("    h.", a.MethodName, "(state, ", cppParse(a.Message, "payload"), ");")
		g.P("  });")
	}
}

func (e cppEmitter) emitRegister(g *protogen.GeneratedFile, s *Service, routerMethod string) {
	g.P("// Registers a ", s.GoName, "Handler with the router.")
	g.P("inline void Register", s.GoName, "(", cppRouter, "& r, ", s.GoName, "Handler& h) {")
	g.P("  r.", routerMethod, "(New", s.GoName, "Dispatch(h));")
	g.P("}")
	g.P()
}

// EmitScaffold writes the generate-once developer stub: one struct per component
// implementing the Handler, with TODO bodies.
func (e cppEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Scaffolded ONCE by angzarr codegen cpp — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interface")
	g.P("// implemented as commands/events are added to the proto.")
	g.P("#pragma once")
	g.P()
	g.P(`#include "`, e.componentInclude(file, s), `"`)
	g.P()
	g.P("namespace ", cppNamespace(file), " {")
	g.P()
	g.P("// Implement ", s.GoName, "Handler here.")
	g.P("class ", s.GoName, " : public ", s.GoName, "Handler {")
	g.P(" public:")
	for _, m := range e.methods(s) {
		g.P("  ", m.results, " ", m.name, "(", m.params, ") override {")
		if m.results == "void" {
			g.P("    // TODO: implement ", s.GoName, "::", m.name)
		} else {
			g.P("    throw std::runtime_error(", cppQuote("TODO: implement "+s.GoName+"::"+m.name), ");")
		}
		g.P("  }")
	}
	g.P("};")
	g.P()
	g.P("}  // namespace ", cppNamespace(file))
	return nil
}

// --- C++ naming helpers -------------------------------------------------------

// cppParse renders the parse of an Any payload into its typed message, routing a
// decode failure through CodedError as ANY_DECODE_FAILED.
func cppParse(m *protogen.Message, anyVar string) string {
	return cppCoded + "::Parse<" + cppType(m) + ">(" + anyVar + ")"
}

func cppGeneric(base, typeArg string) string {
	return base + "<" + typeArg + ">"
}

// cppQuote renders a Go string as a C++ string literal.
func cppQuote(s string) string {
	return `"` + s + `"`
}

func cppNamespace(file *protogen.File) string {
	return cppNamespaceOf(file.Desc)
}

func cppNamespaceOf(fd protoreflect.FileDescriptor) string {
	return strings.ReplaceAll(string(fd.Package()), ".", "::")
}

// cppType computes the fully-qualified C++ type name of a message: the file's
// namespace (package dots→"::") then the nested message path ("::" joined;
// protobuf-cpp exposes nested messages as Outer::Inner).
func cppType(m *protogen.Message) string {
	ns := cppNamespaceOf(m.Desc.ParentFile())
	nested := cppNestedName(m.Desc)
	if ns == "" {
		return nested
	}
	return ns + "::" + nested
}

func cppNestedName(md protoreflect.MessageDescriptor) string {
	parts := []string{string(md.Name())}
	for {
		parent, ok := md.Parent().(protoreflect.MessageDescriptor)
		if !ok {
			break
		}
		parts = append([]string{string(parent.Name())}, parts...)
		md = parent
	}
	return strings.Join(parts, "::")
}

// cppInclude is the generated protobuf header for a proto file (path.proto → path.pb.h).
func cppInclude(fd protoreflect.FileDescriptor) string {
	return strings.TrimSuffix(fd.Path(), ".proto") + ".pb.h"
}

// componentInclude is the gen-relative path of a component's wiring header
// (beside the proto), used by the scaffold to include the interface it stubs.
func (e cppEmitter) componentInclude(file *protogen.File, s *Service) string {
	dir := ""
	if i := strings.LastIndex(file.Desc.Path(), "/"); i >= 0 {
		dir = file.Desc.Path()[:i+1]
	}
	return dir + snake(s.GoName) + "_angzarr.h"
}

// includes collects the .pb.h headers the wiring needs: every referenced
// message's file (state, commands/events, emitted events), sorted + deduped.
func (e cppEmitter) includes(file *protogen.File, services []*Service) []string {
	set := map[string]struct{}{cppInclude(file.Desc): {}}
	add := func(m *protogen.Message) {
		if m != nil {
			set[cppInclude(m.Desc.ParentFile())] = struct{}{}
		}
	}
	for _, s := range services {
		add(s.State)
		for _, h := range s.Handlers {
			add(h.Message)
			for _, em := range h.Emits {
				add(em)
			}
		}
		for _, a := range s.Appliers {
			add(a.Message)
		}
	}
	out := make([]string, 0, len(set))
	for inc := range set {
		out = append(out, inc)
	}
	sort.Strings(out)
	return out
}
