package codegen

// C++ emitter. Each component's wiring is one header-only file (templates must
// live in headers), named <component>_angzarr.h: a public abstract
// <Component>Handler (the strict seam, pure-virtual methods), an inline
// New<Component>Dispatch factory, and an inline Register<Component> — all free
// declarations at namespace scope, unlike Java/C#'s single-outer-class shape
// (C++ has no "one public top-level type per file" restriction to work
// around). Like the C# emitter, the dispatch surfaces are generic in the
// component state message (templates), so the generated wiring is cast-free;
// the single erasing cast lives in the binding's invoker adapters. Type
// references are fully qualified: framework messages under io::angzarr::v1,
// runtime types under angzarr::router, domain messages from the proto package
// (dots→"::"). Google.Protobuf C++ messages are mutable and
// default-constructible, so there is no state factory — the binding
// default-constructs TState.

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	cppRouter       = "angzarr::router::Router"
	cppAggDispatch  = "angzarr::router::AggregateDispatch"
	cppSagaDispatch = "angzarr::router::SagaDispatch"
	cppProjDispatch = "angzarr::router::ProjectorDispatch"
	cppPmDispatch   = "angzarr::router::ProcessManagerDispatch"
	cppRebuilder    = "angzarr::router::Rebuilder"
	cppCctx         = "angzarr::router::CommandContext"
	cppDestinations = "angzarr::router::Destinations"
	cppPack         = "angzarr::router::Pack"
	cppCoded        = "angzarr::router::CodedError"
	cppSagaEmission = "angzarr::router::SagaEmission"
	cppPageContext  = "angzarr::router::PageContext"
	cppFactRecord   = "angzarr::router::FactRecord"
	cppCompensate   = "io::angzarr::v1::Compensate"
	cppAny          = "google::protobuf::Any"
	cppCover        = "io::angzarr::v1::Cover"
	cppEventBook    = "io::angzarr::v1::EventBook"
	cppEventPage    = "io::angzarr::v1::EventPage"
	cppBusinessResp = "io::angzarr::v1::BusinessResponse"
	cppNotification = "io::angzarr::v1::Notification"
	cppRejNotif     = "io::angzarr::v1::RejectionNotification"
	cppProjection   = "io::angzarr::v1::Projection"
	cppPmResponse   = "io::angzarr::v1::ProcessManagerHandleResponse"
	cppVector       = "std::vector"
)

type cppEmitter struct{}

func (cppEmitter) Lang() string { return "cpp" }

func (cppEmitter) WiringPath(file *protogen.File, s *Component) string {
	return componentFile(file, snake(s.BaseName), "_angzarr.h")
}

func (cppEmitter) ScaffoldPath(file *protogen.File, s *Component) string {
	return componentFile(file, snake(s.BaseName), "_angzarr_handler.h")
}

func (e cppEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Component) error {
	g.P("// <auto-generated>")
	g.P("// Code generated by angzarr codegen cpp. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("#pragma once")
	g.P()
	g.P(`#include "angzarr/router/router.h"`)
	for _, inc := range e.includes(file, []*Component{s}) {
		g.P(`#include "`, inc, `"`)
	}
	g.P()
	g.P("namespace ", cppNamespace(file), " {")
	g.P()
	var err error
	switch s.Component.Kind {
	case KindAggregate:
		err = e.emitAggregate(g, s)
	case KindSaga:
		err = e.emitSaga(g, s)
	case KindProjector:
		err = e.emitProjector(g, s)
	case KindProcessManager:
		err = e.emitPM(g, s)
	default:
		err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
	if err != nil {
		return err
	}
	g.P("}  // namespace ", cppNamespace(file))
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e cppEmitter) emitInterface(g *protogen.GeneratedFile, s *Component, doc string) {
	g.P("// The strict business seam for the ", doc, ". Every declared")
	g.P("// command/event must be implemented — a missing handler is a compile error.")
	g.P("class ", s.BaseName, "Handler {")
	g.P(" public:")
	g.P("  virtual ~", s.BaseName, "Handler() = default;")
	for _, m := range e.methods(s) {
		g.P("  virtual ", m.results, " ", m.name, "(", m.params, ") = 0;")
	}
	g.P("};")
	g.P()
}

type cppMethod struct {
	name    string
	params  string
	results string
}

func (e cppEmitter) methods(s *Component) []cppMethod {
	switch s.Component.Kind {
	case KindAggregate:
		return e.aggregateMethods(s)
	case KindSaga:
		return e.sagaMethods(s)
	case KindProjector:
		return e.projectorMethods(s)
	case KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e cppEmitter) aggregateMethods(s *Component) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		results := cppEventBook
		if h.TypedEmit() {
			results = cppVector + "<" + cppType(h.Emits[0]) + ">"
		}
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& cmd, " + state + "& state, const " + cppCctx + "& cctx",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, cppMethod{
			name:    a.MethodName,
			params:  state + "& state, const " + cppType(a.Message) + "& ev, const " + cppPageContext + "& ctx",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, cppMethod{
			name:    r.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppRejNotif + "& rejection, " + state + "& state, const " + cppCctx + "& cctx",
			results: cppBusinessResp,
		})
	}
	for _, f := range s.Facts {
		out = append(out, cppMethod{
			name:    f.MethodName,
			params:  "const " + cppType(f.Message) + "& fact, const " + state + "& state",
			results: "std::optional<" + cppFactRecord + ">",
		})
	}
	for _, u := range s.Undos {
		out = append(out, cppMethod{
			name:    u.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppCompensate + "& compensate, " + state + "& state, const " + cppCctx + "& cctx",
			results: cppBusinessResp,
		})
	}
	return out
}

func (e cppEmitter) sagaMethods(s *Component) []cppMethod {
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& ev, const " + cppDestinations + "& dests, const " + cppPageContext + "& source",
			results: cppSagaEmission,
		})
	}
	return out
}

func (e cppEmitter) projectorMethods(s *Component) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  state + "& projection, const " + cppType(h.Message) + "& ev, const " + cppPageContext + "& ctx",
			results: "void",
		})
	}
	out = append(out, cppMethod{
		name:    projectorFinishMethod,
		params:  state + "& projection, const " + cppEventBook + "& events",
		results: cppProjection,
	})
	return out
}

func (e cppEmitter) pmMethods(s *Component) []cppMethod {
	state := cppType(s.State)
	var out []cppMethod
	for _, h := range s.Handlers {
		out = append(out, cppMethod{
			name:    h.MethodName,
			params:  "const " + cppType(h.Message) + "& ev, " + state + "& state, const " + cppDestinations + "& dests, const " + cppCover + "& triggerCover",
			results: cppPmResponse,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, cppMethod{
			name:    a.MethodName,
			params:  state + "& state, const " + cppType(a.Message) + "& ev, const " + cppPageContext + "& ctx",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, cppMethod{
			name:    r.MethodName,
			params:  "const " + cppNotification + "& n, const " + cppRejNotif + "& rejection, " + state + "& state",
			results: cppPmResponse,
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e cppEmitter) emitAggregate(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" aggregate")
	state := cppType(s.State)
	disp := cppGeneric(cppAggDispatch, state)
	g.P("// Populates the aggregate table from the proto declaration.")
	g.P("inline ", disp, " New", s.BaseName, "Dispatch(", s.BaseName, "Handler& h) {")
	g.P("  ", cppGeneric(cppRebuilder, state), " rebuilder;")
	g.P("  rebuilder.WithSnapshot([](", state, "& state, const ", cppAny, "& payload) {")
	g.P("    ", cppCoded, "::Merge(state, payload);")
	g.P("  });")
	emitCppAppliers(g, s, state)
	g.P("  ", disp, " dispatch(", cppQuote(s.BaseName), ", ", cppQuote(s.Component.Domain), ", std::move(rebuilder));")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnCommand(", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& cmdAny, ", state, "& state, const ", cppCctx, "& cctx) -> ", cppEventBook, " {")
		g.P("    auto cmd = ", cppParse(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("    auto events = h.", h.MethodName, "(cmd, state, cctx);")
			g.P("    ", cppEventBook, " book;")
			g.P("    for (const auto& ev : events) {")
			g.P("      *book.add_pages()->mutable_event() = ", cppPack, "::Wrap(ev);")
			g.P("    }")
			g.P("    return book;")
		} else {
			g.P("    return h.", h.MethodName, "(cmd, state, cctx);")
		}
		g.P("  });")
	}
	for _, r := range s.Rejections {
		g.P("  dispatch.OnRejected(", cppQuote(r.Key), ", [&h](const ", cppNotification, "& n, const ", cppRejNotif, "& rejection, ", state, "& state, const ", cppCctx, "& cctx) {")
		g.P("    return h.", r.MethodName, "(n, rejection, state, cctx);")
		g.P("  });")
	}
	for _, f := range s.Facts {
		g.P("  dispatch.OnFact(", cppQuote(fqName(f.Message)), ", [&h](const ", cppAny, "& factAny, const ", state, "& state) -> ", cppFactRecord, " {")
		g.P("    auto fact = ", cppParse(f.Message, "factAny"), ";")
		g.P("    auto rec = h.", f.MethodName, "(fact, state);")
		g.P("    if (!rec) return factAny;")
		g.P("    return *rec;")
		g.P("  });")
	}
	for _, u := range s.Undos {
		g.P("  dispatch.OnUndo(", cppQuote(u.Command), ", [&h](const ", cppNotification, "& n, const ", cppCompensate, "& compensate, ", state, "& state, const ", cppCctx, "& cctx) {")
		g.P("    return h.", u.MethodName, "(n, compensate, state, cctx);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterAggregate")
	return nil
}

func (e cppEmitter) emitSaga(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" saga")
	g.P("// Populates the saga table from the proto declaration.")
	g.P("inline ", cppSagaDispatch, " New", s.BaseName, "Dispatch(", s.BaseName, "Handler& h) {")
	g.P("  ", cppSagaDispatch, " dispatch(", cppQuote(s.BaseName), ", ", cppQuote(s.Component.InputDomain), ", {", quoteJoin(s.Component.OutputDomains, cppQuote), "});")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEventWithContext(", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& eventAny, const ", cppDestinations, "& dests, const ", cppPageContext, "& source) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    return h.", h.MethodName, "(ev, dests, source);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterSaga")
	return nil
}

func (e cppEmitter) emitProjector(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" projector")
	state := cppType(s.State)
	disp := cppGeneric(cppProjDispatch, state)
	g.P("// Populates the projector table from the proto declaration.")
	g.P("inline ", disp, " New", s.BaseName, "Dispatch(", s.BaseName, "Handler& h) {")
	g.P("  ", disp, " dispatch(", cppQuote(s.BaseName), ");")
	// Domain filter (Component.ProjectorDomains); omitted when empty so the
	// runtime default, consume every domain, applies.
	if len(s.ProjectorDomains) > 0 {
		g.P("  dispatch.ForDomains({", quoteJoin(s.ProjectorDomains, cppQuote), "});")
	}
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEventWithContext(", cppQuote(fqName(h.Message)), ", [&h](", state, "& projection, const ", cppAny, "& eventAny, const ", cppPageContext, "& ctx) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    h.", h.MethodName, "(projection, ev, ctx);")
		g.P("  });")
	}
	g.P("  dispatch.Finish([&h](", state, "& projection, const ", cppEventBook, "& events) {")
	g.P("    return h.Finish(projection, events);")
	g.P("  });")
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterProjector")
	return nil
}

func (e cppEmitter) emitPM(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" process manager")
	state := cppType(s.State)
	disp := cppGeneric(cppPmDispatch, state)
	g.P("// Populates the PM table from the proto declaration.")
	g.P("inline ", disp, " New", s.BaseName, "Dispatch(", s.BaseName, "Handler& h) {")
	g.P("  ", cppGeneric(cppRebuilder, state), " rebuilder;")
	g.P("  rebuilder.WithSnapshot([](", state, "& state, const ", cppAny, "& payload) {")
	g.P("    ", cppCoded, "::Merge(state, payload);")
	g.P("  });")
	emitCppAppliers(g, s, state)
	g.P("  ", disp, " dispatch(", cppQuote(s.BaseName), ", ", cppQuote(s.Component.Domain), ", {", quoteJoin(s.Component.OutputDomains, cppQuote), "}, std::move(rebuilder));")
	for _, h := range s.Handlers {
		g.P("  dispatch.OnEventWithCover(", cppQuote(h.SourceDomain), ", ", cppQuote(fqName(h.Message)), ", [&h](const ", cppAny, "& eventAny, ", state, "& state, const ", cppDestinations, "& dests, const ", cppCover, "& triggerCover) {")
		g.P("    auto ev = ", cppParse(h.Message, "eventAny"), ";")
		g.P("    return h.", h.MethodName, "(ev, state, dests, triggerCover);")
		g.P("  });")
	}
	for _, r := range s.Rejections {
		g.P("  dispatch.OnRejectedWithResponse(", cppQuote(r.Key), ", [&h](const ", cppNotification, "& n, const ", cppRejNotif, "& rejection, ", state, "& state) {")
		g.P("    return h.", r.MethodName, "(n, rejection, state);")
		g.P("  });")
	}
	g.P("  return dispatch;")
	g.P("}")
	g.P()
	e.emitRegister(g, s, "RegisterProcessManager")
	return nil
}

// emitCppAppliers registers each event applier on the rebuilder. Identical for
// aggregates and process managers (both rebuild their own state).
func emitCppAppliers(g *protogen.GeneratedFile, s *Component, state string) {
	for _, a := range s.Appliers {
		g.P("  rebuilder.ApplyWithContext(", cppQuote(fqName(a.Message)), ", [&h](", state, "& state, const ", cppAny, "& payload, const ", cppPageContext, "& ctx) {")
		g.P("    h.", a.MethodName, "(state, ", cppParse(a.Message, "payload"), ", ctx);")
		g.P("  });")
	}
}

func (e cppEmitter) emitRegister(g *protogen.GeneratedFile, s *Component, routerMethod string) {
	g.P("// Registers a ", s.BaseName, "Handler with the router.")
	g.P("inline void Register", s.BaseName, "(", cppRouter, "& r, ", s.BaseName, "Handler& h) {")
	g.P("  r.", routerMethod, "(New", s.BaseName, "Dispatch(h));")
	g.P("}")
	g.P()
}

// EmitScaffoldComponent writes the generate-once developer stub: a class
// implementing the component's Handler, with TODO bodies.
func (e cppEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Component) error {
	g.P("// Scaffolded ONCE by angzarr codegen cpp — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interface")
	g.P("// implemented as commands/events are added to the proto.")
	g.P("#pragma once")
	g.P()
	g.P("#include <stdexcept>")
	g.P()
	g.P(`#include "`, e.componentInclude(file, s), `"`)
	g.P()
	g.P("namespace ", cppNamespace(file), " {")
	g.P()
	g.P("// Implement ", s.BaseName, "Handler here.")
	g.P("class ", s.StubName, " : public ", s.BaseName, "Handler {")
	g.P(" public:")
	for _, m := range e.methods(s) {
		g.P("  ", m.results, " ", m.name, "(", m.params, ") override {")
		if m.results == "void" {
			g.P("    // TODO: implement ", s.StubName, "::", m.name)
		} else {
			g.P("    throw std::runtime_error(", cppQuote("TODO: implement "+s.StubName+"::"+m.name), ");")
		}
		g.P("  }")
	}
	g.P("};")
	g.P()
	g.P("}  // namespace ", cppNamespace(file))
	return nil
}

// --- C++ naming helpers -------------------------------------------------------

// cppParse renders the parse of an Any payload into its typed message, routing a
// decode failure through CodedError as ANY_DECODE_FAILED.
func cppParse(m *protogen.Message, anyVar string) string {
	return cppCoded + "::Parse<" + cppType(m) + ">(" + anyVar + ")"
}

func cppGeneric(base, typeArg string) string {
	return base + "<" + typeArg + ">"
}

// cppQuote renders a C++ string literal.
func cppQuote(s string) string { return quoteLiteral(s) }

func cppNamespace(file *protogen.File) string {
	return cppNamespaceOf(file.Desc)
}

func cppNamespaceOf(fd protoreflect.FileDescriptor) string {
	return strings.ReplaceAll(string(fd.Package()), ".", "::")
}

// cppType computes the fully-qualified C++ type name of a message: the file's
// namespace (package dots→"::") then the nested message path ("::" joined;
// protobuf-cpp exposes nested messages as Outer::Inner).
func cppType(m *protogen.Message) string {
	ns := cppNamespaceOf(m.Desc.ParentFile())
	nested := cppNestedName(m.Desc)
	if ns == "" {
		return nested
	}
	return ns + "::" + nested
}

// cppNestedName joins a message's name path within its file with "::"
// (protobuf-cpp exposes nested messages as Outer::Inner).
func cppNestedName(md protoreflect.MessageDescriptor) string {
	return strings.Join(nestedNames(md), "::")
}

// cppInclude is the generated protobuf header for a proto file (path.proto → path.pb.h).
func cppInclude(fd protoreflect.FileDescriptor) string {
	return strings.TrimSuffix(fd.Path(), ".proto") + ".pb.h"
}

// componentInclude is the output-root-relative path of a component's wiring
// header, used by the scaffold to include the interface it stubs.
func (e cppEmitter) componentInclude(file *protogen.File, s *Component) string {
	return e.WiringPath(file, s)
}

// includes collects the .pb.h headers the wiring needs: every referenced
// message's file (state, commands/events, emitted events), sorted + deduped.
func (e cppEmitter) includes(file *protogen.File, services []*Component) []string {
	set := map[string]struct{}{cppInclude(file.Desc): {}}
	add := func(m *protogen.Message) {
		if m != nil {
			set[cppInclude(m.Desc.ParentFile())] = struct{}{}
		}
	}
	for _, s := range services {
		add(s.State)
		for _, h := range s.Handlers {
			add(h.Message)
			for _, em := range h.Emits {
				add(em)
			}
		}
		for _, a := range s.Appliers {
			add(a.Message)
		}
	}
	out := make([]string, 0, len(set))
	for inc := range set {
		out = append(out, inc)
	}
	sort.Strings(out)
	return out
}
