package codegen

// C# emitter. Like the Java emitter, each proto file's components are emitted
// into ONE wiring file (the conformance fixtures, a separate namespace, import
// the handler types) as a single public static outer class (named
// <protofile>_angzarr) holding a public nested <Component>Handler interface, a
// New<Component>Dispatch factory, and a Register<Component> convenience per
// component. Type references are fully qualified (no using management):
// framework message types under the Angzarr namespace, runtime types under
// Angzarr.Router, and domain message types computed from the file's
// csharp_namespace (or the PascalCase package). Unlike Java, Google.Protobuf
// messages are MUTABLE — state is the message itself (no Builder), the factory
// is () => new <State>(), and appliers fold via property setters / MergeFrom.

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	csRouter       = "Angzarr.Router.Router"
	csAggDispatch  = "Angzarr.Router.AggregateDispatch"
	csSagaDispatch = "Angzarr.Router.SagaDispatch"
	csProjDispatch = "Angzarr.Router.ProjectorDispatch"
	csPmDispatch   = "Angzarr.Router.ProcessManagerDispatch"
	csRebuilder    = "Angzarr.Router.Rebuilder"
	csCctx         = "Angzarr.Router.CommandContext"
	csDestinations = "Angzarr.Router.Destinations"
	csPack         = "Angzarr.Router.Pack"
	csCoded        = "Angzarr.Router.CodedError"
	csSagaEmission = "Angzarr.Router.SagaEmission"
	csPmRejection  = "Angzarr.Router.PmRejection"
	csEventBook    = "Angzarr.EventBook"
	csEventPage    = "Angzarr.EventPage"
	csBusinessResp = "Angzarr.BusinessResponse"
	csNotification = "Angzarr.Notification"
	csRejNotif     = "Angzarr.RejectionNotification"
	csProjection   = "Angzarr.Projection"
	csPmResponse   = "Angzarr.ProcessManagerHandleResponse"
	csList         = "System.Collections.Generic.IReadOnlyList"
)

type csharpEmitter struct{}

func (csharpEmitter) Lang() string           { return "csharp" }
func (csharpEmitter) Suffix() string         { return "_angzarr.cs" }
func (csharpEmitter) ScaffoldSuffix() string { return "_angzarr_handler.cs" }

func (e csharpEmitter) EmitFile(g *protogen.GeneratedFile, file *protogen.File, services []*Service) error {
	g.P("// <auto-generated/>")
	g.P("// Code generated by angzarr codegen csharp. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("namespace ", csNamespace(file), ";")
	g.P()
	g.P("public static class ", csWiringClass(file))
	g.P("{")
	for _, s := range services {
		var err error
		switch s.Component.Kind {
		case KindAggregate:
			err = e.emitAggregate(g, s)
		case KindSaga:
			err = e.emitSaga(g, s)
		case KindProjector:
			err = e.emitProjector(g, s)
		case KindProcessManager:
			err = e.emitPM(g, s)
		default:
			err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
		}
		if err != nil {
			return err
		}
	}
	g.P("}")
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e csharpEmitter) emitInterface(g *protogen.GeneratedFile, s *Service, doc string) {
	g.P("    /// <summary>The strict business seam for the ", doc, ". Every declared")
	g.P("    /// command/event must be implemented — a missing handler is a compile error.</summary>")
	g.P("    public interface ", s.GoName, "Handler")
	g.P("    {")
	for _, m := range e.methods(s) {
		g.P("        ", m.results, " ", m.name, "(", m.params, ");")
	}
	g.P("    }")
	g.P()
}

// csMethod is one handler method, shared by the interface and the scaffold.
type csMethod struct {
	name    string
	params  string
	results string // "void" or a type
}

func (e csharpEmitter) methods(s *Service) []csMethod {
	switch s.Component.Kind {
	case KindAggregate:
		return e.aggregateMethods(s)
	case KindSaga:
		return e.sagaMethods(s)
	case KindProjector:
		return e.projectorMethods(s)
	case KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e csharpEmitter) aggregateMethods(s *Service) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		results := csEventBook
		if h.TypedEmit() {
			results = csList + "<" + csType(h.Emits[0]) + ">"
		}
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " cmd, " + state + " state, " + csCctx + " cctx",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, csMethod{
			name:    a.MethodName,
			params:  state + " state, " + csType(a.Message) + " ev",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, csMethod{
			name:    r.MethodName,
			params:  csNotification + " n, " + csRejNotif + " rejection, " + state + " state, " + csCctx + " cctx",
			results: csBusinessResp,
		})
	}
	return out
}

func (e csharpEmitter) sagaMethods(s *Service) []csMethod {
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " ev, " + csDestinations + " dests",
			results: csSagaEmission,
		})
	}
	for _, r := range s.Rejections {
		out = append(out, csMethod{
			name:    r.MethodName,
			params:  csNotification + " n, " + csRejNotif + " rejection",
			results: csList + "<" + csEventBook + ">",
		})
	}
	return out
}

func (e csharpEmitter) projectorMethods(s *Service) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  state + " projection, " + csType(h.Message) + " ev",
			results: "void",
		})
	}
	out = append(out, csMethod{
		name:    "Finish",
		params:  state + " projection, " + csEventBook + " events",
		results: csProjection,
	})
	return out
}

func (e csharpEmitter) pmMethods(s *Service) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " ev, " + state + " state, " + csDestinations + " dests",
			results: csPmResponse,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, csMethod{
			name:    a.MethodName,
			params:  state + " state, " + csType(a.Message) + " ev",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, csMethod{
			name:    r.MethodName,
			params:  csNotification + " n, " + csRejNotif + " rejection, " + state + " state",
			results: csPmRejection,
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e csharpEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" aggregate")
	state := csType(s.State)
	g.P("    /// <summary>Populates the aggregate table from the proto declaration.</summary>")
	g.P("    public static ", csAggDispatch, " New", s.GoName, "Dispatch(", s.GoName, "Handler h)")
	g.P("    {")
	g.P("        var rebuilder = new ", csRebuilder, "(() => new ", state, "());")
	g.P("        rebuilder.WithSnapshot((state, payload) => ((", state, ")state).MergeFrom(payload.Value));")
	for _, a := range s.Appliers {
		g.P("        rebuilder.Apply(", quote(a.fqType()), ", (state, payload) =>")
		g.P("            h.", a.MethodName, "((", state, ")state, ", csParse(a.Message, "payload.Value"), "));")
	}
	g.P("        return new ", csAggDispatch, "(", quote(s.GoName), ", ", quote(s.Component.InputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("            .OnCommand(", quote(string(h.Message.Desc.FullName())), ", (cmdAny, state, cctx) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " cmd = ", csParseAny(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("                var events = h.", h.MethodName, "(cmd, (", state, ")state, cctx);")
			g.P("                var book = new ", csEventBook, "();")
			g.P("                foreach (var ev in events)")
			g.P("                {")
			g.P("                    book.Pages.Add(new ", csEventPage, " { Event = ", csPack, ".Pack(ev) });")
			g.P("                }")
			g.P("                return book;")
		} else {
			g.P("                return h.", h.MethodName, "(cmd, (", state, ")state, cctx);")
		}
		g.P("            })")
	}
	for _, r := range s.Rejections {
		g.P("            .OnRejected(", quote(r.Command), ", (n, rejection, state, cctx) =>")
		g.P("                h.", r.MethodName, "(n, rejection, (", state, ")state, cctx))")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterAggregate")
	return nil
}

func (e csharpEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" saga")
	g.P("    /// <summary>Populates the saga table from the proto declaration.</summary>")
	g.P("    public static ", csSagaDispatch, " New", s.GoName, "Dispatch(", s.GoName, "Handler h)")
	g.P("    {")
	g.P("        return new ", csSagaDispatch, "(", quote(s.GoName), ", ", quote(s.Component.InputDomain), ", ", quote(s.Component.OutputDomain), ")")
	for _, h := range s.Handlers {
		g.P("            .OnEvent(", quote(string(h.Message.Desc.FullName())), ", (eventAny, dests) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                return h.", h.MethodName, "(ev, dests);")
		g.P("            })")
	}
	for _, r := range s.Rejections {
		g.P("            .OnRejected(", quote(r.Command), ", (n, rejection) => h.", r.MethodName, "(n, rejection))")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterSaga")
	return nil
}

func (e csharpEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" projector")
	state := csType(s.State)
	g.P("    /// <summary>Populates the projector table from the proto declaration.</summary>")
	g.P("    public static ", csProjDispatch, " New", s.GoName, "Dispatch(", s.GoName, "Handler h)")
	g.P("    {")
	g.P("        return new ", csProjDispatch, "(", quote(s.GoName), ", () => new ", state, "())")
	g.P("            .ForDomains(", quote(s.Component.InputDomain), ")")
	for _, h := range s.Handlers {
		g.P("            .OnEvent(", quote(string(h.Message.Desc.FullName())), ", (projection, eventAny) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                h.", h.MethodName, "((", state, ")projection, ev);")
		g.P("            })")
	}
	g.P("            .Finish((projection, events) => h.Finish((", state, ")projection, events));")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterProjector")
	return nil
}

func (e csharpEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" process manager")
	state := csType(s.State)
	g.P("    /// <summary>Populates the PM table from the proto declaration.</summary>")
	g.P("    public static ", csPmDispatch, " New", s.GoName, "Dispatch(", s.GoName, "Handler h)")
	g.P("    {")
	g.P("        var rebuilder = new ", csRebuilder, "(() => new ", state, "());")
	g.P("        rebuilder.WithSnapshot((state, payload) => ((", state, ")state).MergeFrom(payload.Value));")
	for _, a := range s.Appliers {
		g.P("        rebuilder.Apply(", quote(a.fqType()), ", (state, payload) =>")
		g.P("            h.", a.MethodName, "((", state, ")state, ", csParse(a.Message, "payload.Value"), "));")
	}
	g.P("        return new ", csPmDispatch, "(", quote(s.GoName), ", ", quote(s.Component.OutputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("            .OnEvent(", quote(h.SourceDomain), ", ", quote(string(h.Message.Desc.FullName())), ", (eventAny, state, dests) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                return h.", h.MethodName, "(ev, (", state, ")state, dests);")
		g.P("            })")
	}
	for _, r := range s.Rejections {
		g.P("            .OnRejected(", quote(r.Command), ", (n, rejection, state) =>")
		g.P("                h.", r.MethodName, "(n, rejection, (", state, ")state))")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterProcessManager")
	return nil
}

func (e csharpEmitter) emitRegister(g *protogen.GeneratedFile, s *Service, routerMethod string) {
	g.P("    /// <summary>Registers a ", s.GoName, "Handler with the router.</summary>")
	g.P("    public static void Register", s.GoName, "(", csRouter, " r, ", s.GoName, "Handler h)")
	g.P("    {")
	g.P("        r.", routerMethod, "(New", s.GoName, "Dispatch(h));")
	g.P("    }")
	g.P()
}

// EmitScaffold writes the generate-once developer stub: one outer static class
// per proto file with a public sealed <Component> stub implementing the Handler.
func (e csharpEmitter) EmitScaffold(g *protogen.GeneratedFile, file *protogen.File, services []*Service) error {
	g.P("// Scaffolded ONCE by angzarr codegen csharp — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interfaces")
	g.P("// implemented as commands/events are added to the proto.")
	g.P()
	g.P("namespace ", csNamespace(file), ";")
	g.P()
	g.P("public static class ", csScaffoldClass(file))
	g.P("{")
	for _, s := range services {
		g.P("    /// <summary>Implement ", s.GoName, "Handler here.</summary>")
		g.P("    public sealed class ", s.GoName, " : ", csWiringClass(file), ".", s.GoName, "Handler")
		g.P("    {")
		for _, m := range e.methods(s) {
			g.P("        public ", m.results, " ", m.name, "(", m.params, ")")
			g.P("        {")
			if m.results == "void" {
				g.P("            // TODO: implement ", s.GoName, ".", m.name)
			} else {
				g.P("            throw new System.NotImplementedException(", quote("TODO: implement "+s.GoName+"."+m.name), ");")
			}
			g.P("        }")
		}
		g.P("    }")
		g.P()
	}
	g.P("}")
	return nil
}

// --- C# naming helpers --------------------------------------------------------

// csParseAny renders the parse of an Any payload into the typed message, routing
// a decode failure through CodedError as ANY_DECODE_FAILED.
func csParseAny(m *protogen.Message, anyVar string) string {
	return csCoded + ".Parse(" + csType(m) + ".Parser, " + anyVar + ")"
}

// csParse parses a typed message directly from a ByteString (applier payloads).
func csParse(m *protogen.Message, bytesVar string) string {
	return csType(m) + ".Parser.ParseFrom(" + bytesVar + ")"
}

func csWiringClass(file *protogen.File) string {
	return protoBase(file) + "_angzarr"
}

func csScaffoldClass(file *protogen.File) string {
	return protoBase(file) + "_angzarr_handler"
}

// csNamespace resolves a file's C# namespace: the csharp_namespace option, else
// each proto package segment PascalCased and joined with ".".
func csNamespace(file *protogen.File) string {
	return csNamespaceOf(file.Desc)
}

func csNamespaceOf(fd protoreflect.FileDescriptor) string {
	if opts, ok := fd.Options().(*descriptorpb.FileOptions); ok && opts.CsharpNamespace != nil {
		return opts.GetCsharpNamespace()
	}
	return pascalNamespace(string(fd.Package()))
}

// pascalNamespace PascalCases each dotted package segment (test.counter →
// Test.Counter), matching protoc's default C# namespace derivation.
func pascalNamespace(pkg string) string {
	if pkg == "" {
		return ""
	}
	parts := strings.Split(pkg, ".")
	for i, p := range parts {
		parts[i] = snakeToPascal(p)
	}
	return strings.Join(parts, ".")
}

// csType computes the fully-qualified C# type name of a message: the file's C#
// namespace, then the nested message path joined by ".Types." (Google.Protobuf
// nests message types under a Types container).
func csType(m *protogen.Message) string {
	fd := m.Desc.ParentFile()
	ns := csNamespaceOf(fd)
	nested := csNestedName(m.Desc)
	if ns == "" {
		return nested
	}
	return ns + "." + nested
}

// csNestedName joins a message's name path within its file, with ".Types."
// between levels (Outer.Types.Inner).
func csNestedName(md protoreflect.MessageDescriptor) string {
	parts := []string{string(md.Name())}
	for {
		parent, ok := md.Parent().(protoreflect.MessageDescriptor)
		if !ok {
			break
		}
		parts = append([]string{string(parent.Name())}, parts...)
		md = parent
	}
	return strings.Join(parts, ".Types.")
}
