package codegen

// Go emitter. For each declared component it emits two files:
//
//   - the WIRING file (Suffix, e.g. *_angzarr.pb.go): a STRICT
//     <Component>Handler interface (one typed method per declared
//     command/event — a missing handler is a compile error, never a silent
//     no-op), a New<Component>Dispatch constructor that populates the
//     binding's dispatch table with unmarshal thunks calling the typed
//     methods, and a Register<Component> convenience hiding the per-kind
//     registration split. This file is regenerated wholesale every run.
//
//   - the SCAFFOLD file (ScaffoldSuffix, e.g. *_angzarr_handler.go): a stub
//     <Component> struct implementing the interface, one TODO method per
//     declared command/event. It is generated ONCE — the plugin skips it when
//     the file already exists — then owned and edited by the developer;
//     regeneration never overwrites it. A compile-time
//     `var _ <Component>Handler = <Component>{}` assertion means a command or
//     event added to the proto surfaces as a build error pointing the
//     developer at the new method to implement.
//
// Generated code contains no dispatch logic and no gRPC — it is a thin table
// population over the angzarr-router Go binding (ffirouter), and the envelope
// stays google.protobuf.Any end to end. An aggregate command handler that
// declares exactly one emitted event type returns that typed slice and the
// wiring builds the EventBook; otherwise it returns the raw EventBook escape
// hatch (multi-type emission, custom covers, snapshots).

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	angzarrPkg = protogen.GoImportPath("github.com/angzarr-io/angzarr-router/bindings/go")
	angzarrPb  = protogen.GoImportPath("github.com/angzarr-io/angzarr-router/bindings/go/gen/io/angzarr/v1")
	anypbPkg   = protogen.GoImportPath("google.golang.org/protobuf/types/known/anypb")
)

type goEmitter struct{}

func (goEmitter) Lang() string { return "go" }

func (goEmitter) WiringPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr.pb.go")
}

func (goEmitter) ScaffoldPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr_handler.go")
}

func (e goEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Code generated by angzarr codegen go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	switch s.Component.Kind {
	case KindSaga:
		return e.emitSaga(g, s)
	case KindAggregate:
		return e.emitAggregate(g, s)
	case KindProcessManager:
		return e.emitPM(g, s)
	case KindProjector:
		return e.emitProjector(g, s)
	default:
		return fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
}

// EmitScaffoldComponent writes the generate-once handler stub: a struct
// implementing the component's Handler interface, each method with a TODO body
// and a compile-time interface-satisfaction assertion.
func (e goEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Scaffolded ONCE by angzarr codegen go — this file is YOURS.")
	g.P("//")
	g.P("// Regeneration will NOT overwrite this file. It is your responsibility to")
	g.P("// keep the generated <Component>Handler interface implemented: when a")
	g.P("// command or event is added to the proto, the var _ assertion below fails")
	g.P("// the build until you add the new method here.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	methods, err := e.methods(g, s)
	if err != nil {
		return err
	}
	g.P("// ", s.GoName, " implements ", s.GoName, "Handler.")
	g.P("type ", s.GoName, " struct{}")
	g.P()
	g.P("var _ ", s.GoName, "Handler = ", s.GoName, "{}")
	g.P()
	for _, m := range methods {
		g.P("func (", s.GoName, ") ", m.name, m.params, m.results, " {")
		if m.results == "" {
			g.P("\t// TODO: implement ", s.GoName, ".", m.name)
		} else {
			g.P("\tpanic(", quote("TODO: implement "+s.GoName+"."+m.name), ")")
		}
		g.P("}")
		g.P()
	}
	return nil
}

// methodSig is one generated handler method's signature, rendered once and
// shared by the strict interface and the scaffold stub so the two never drift.
type methodSig struct {
	name    string
	params  string // includes the enclosing parentheses
	results string // includes a leading space, or "" for a no-result method
}

// methods returns every handler method for a component, in interface order.
func (e goEmitter) methods(g *protogen.GeneratedFile, s *Service) ([]methodSig, error) {
	switch s.Component.Kind {
	case KindSaga:
		return e.sagaMethods(g, s), nil
	case KindAggregate:
		return e.aggregateMethods(g, s), nil
	case KindProcessManager:
		return e.pmMethods(g, s), nil
	case KindProjector:
		return e.projectorMethods(g, s), nil
	default:
		return nil, fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
}

// emitInterface writes the strict <Name>Handler interface from the shared
// method signatures.
func emitInterface(g *protogen.GeneratedFile, name, doc string, methods []methodSig) {
	g.P("// ", name, "Handler is the strict business seam for the ", doc, ".")
	g.P("// Every declared command/event must be implemented — a missing handler is")
	g.P("// a compile error, never a silent no-op.")
	g.P("type ", name, "Handler interface {")
	for _, m := range methods {
		g.P("\t", m.name, m.params, m.results)
	}
	g.P("}")
	g.P()
}

// idents used across emitters
func ident(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return g.QualifiedGoIdent(pkg.Ident(name))
}

func star(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return "*" + ident(g, pkg, name)
}

func (goEmitter) sagaMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	dests := star(g, angzarrPkg, "Destinations")
	cmdBook := star(g, angzarrPb, "CommandBook")
	evtBook := star(g, angzarrPb, "EventBook")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", dests " + dests + ")",
			results: " ([]" + cmdBook + ", []" + evtBook + ", error)",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ")",
			results: " ([]" + evtBook + ", error)",
		})
	}
	return out
}

func (goEmitter) aggregateMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	bizResp := star(g, angzarrPb, "BusinessResponse")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	cctx := ident(g, angzarrPkg, "CommandContext")
	var out []methodSig
	for _, h := range s.Handlers {
		results := " (" + evtBook + ", error)"
		if h.TypedEmit() {
			results = " ([]*" + g.QualifiedGoIdent(h.Emits[0].GoIdent) + ", error)"
		}
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(cmd *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", state " + statePtr + ", cctx " + cctx + ")",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, methodSig{
			name:   a.MethodName,
			params: "(state " + statePtr + ", event *" + g.QualifiedGoIdent(a.Message.GoIdent) + ")",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ", state " + statePtr + ", cctx " + cctx + ")",
			results: " (" + bizResp + ", error)",
		})
	}
	return out
}

func (goEmitter) pmMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	dests := star(g, angzarrPkg, "Destinations")
	pmResp := star(g, angzarrPb, "ProcessManagerHandleResponse")
	evtBook := star(g, angzarrPb, "EventBook")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", state " + statePtr + ", dests " + dests + ")",
			results: " (" + pmResp + ", error)",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, methodSig{
			name:   a.MethodName,
			params: "(state " + statePtr + ", event *" + g.QualifiedGoIdent(a.Message.GoIdent) + ")",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ", state " + statePtr + ")",
			results: " ([]" + evtBook + ", " + notif + ", error)",
		})
	}
	return out
}

func (goEmitter) projectorMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	projection := star(g, angzarrPb, "Projection")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(projection " + statePtr + ", event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ")",
			results: " error",
		})
	}
	out = append(out, methodSig{
		name:    "Finish",
		params:  "(projection " + statePtr + ", events " + evtBook + ")",
		results: " (" + projection + ", error)",
	})
	return out
}

func (e goEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	dests := star(g, angzarrPkg, "Destinations")
	cmdBook := star(g, angzarrPb, "CommandBook")
	evtBook := star(g, angzarrPb, "EventBook")

	emitInterface(g, name, name+" saga", e.sagaMethods(g, s))
	g.P("// New", name, "Dispatch populates the saga table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "SagaDispatch"), " {")
	g.P("dispatch := ", ident(g, angzarrPkg, "NewSagaDispatch"), "(", quote(name), ", ", quote(component.InputDomain), ", ", quote(component.OutputDomain), ")")
	for _, h := range s.Handlers {
		g.P("dispatch.OnEvent(", quoteFQ(h.Message), ", func(eventAny ", star(g, anypbPkg, "Any"), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error) {")
		emitDecode(g, "event", "eventAny", h.Message, "nil, nil, ")
		g.P("return h.", h.MethodName, "(event, dests)")
		g.P("})")
	}
	for _, r := range s.Rejections {
		g.P("dispatch.OnRejected(", quote(r.Command), ", h.", r.MethodName, ")")
	}
	g.P("return dispatch")
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn r.RegisterSaga(New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	evtPage := ident(g, angzarrPb, "EventPage")
	evtPageEvent := ident(g, angzarrPb, "EventPage_Event")
	cctx := ident(g, angzarrPkg, "CommandContext")

	emitInterface(g, name, name+" aggregate", e.aggregateMethods(g, s))
	g.P("// New", name, "Dispatch populates the aggregate table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "AggregateDispatch"), "[", statePtr, "] {")
	g.P("rebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	emitSnapshotLoader(g, s.State)
	emitAppliers(g, s, statePtr)
	g.P("dispatch := ", ident(g, angzarrPkg, "NewAggregateDispatch"), "(", quote(name), ", ", quote(component.InputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("dispatch.OnCommand(", quoteFQ(h.Message), ", func(cmdAny ", star(g, anypbPkg, "Any"), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error) {")
		emitDecode(g, "cmd", "cmdAny", h.Message, "nil, ")
		if h.TypedEmit() {
			g.P("events, err := h.", h.MethodName, "(cmd, state, cctx)")
			g.P("if err != nil { return nil, err }")
			g.P("pages := make([]*", evtPage, ", len(events))")
			g.P("for i, ev := range events {")
			g.P("payload, err := ", ident(g, angzarrPkg, "Pack"), "(ev)")
			g.P("if err != nil { return nil, err }")
			g.P("pages[i] = &", evtPage, "{Payload: &", evtPageEvent, "{Event: payload}}")
			g.P("}")
			g.P("return &", ident(g, angzarrPb, "EventBook"), "{Pages: pages}, nil")
		} else {
			g.P("return h.", h.MethodName, "(cmd, state, cctx)")
		}
		g.P("})")
	}
	for _, r := range s.Rejections {
		g.P("dispatch.OnRejected(", quote(r.Command), ", h.", r.MethodName, ")")
	}
	g.P("return dispatch")
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterAggregate"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	dests := star(g, angzarrPkg, "Destinations")
	pmResp := star(g, angzarrPb, "ProcessManagerHandleResponse")

	emitInterface(g, name, name+" process manager", e.pmMethods(g, s))
	g.P("// New", name, "Dispatch populates the PM table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProcessManagerDispatch"), "[", statePtr, "] {")
	g.P("rebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	emitSnapshotLoader(g, s.State)
	emitAppliers(g, s, statePtr)
	g.P("dispatch := ", ident(g, angzarrPkg, "NewProcessManagerDispatch"), "(", quote(name), ", ", quote(component.OutputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("dispatch.OnEvent(", quote(h.SourceDomain), ", ", quoteFQ(h.Message), ", func(eventAny ", star(g, anypbPkg, "Any"), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error) {")
		emitDecode(g, "event", "eventAny", h.Message, "nil, ")
		g.P("return h.", h.MethodName, "(event, state, dests)")
		g.P("})")
	}
	for _, r := range s.Rejections {
		g.P("dispatch.OnRejected(", quote(r.Command), ", h.", r.MethodName, ")")
	}
	g.P("return dispatch")
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterProcessManager"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)

	emitInterface(g, name, name+" projector", e.projectorMethods(g, s))
	g.P("// New", name, "Dispatch populates the projector table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProjectorDispatch"), "[", statePtr, "] {")
	g.P("dispatch := ", ident(g, angzarrPkg, "NewProjectorDispatch"), "(", quote(name), ", func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	g.P("dispatch.ForDomains(", quote(component.InputDomain), ")")
	for _, h := range s.Handlers {
		g.P("dispatch.OnEvent(", quoteFQ(h.Message), ", func(projection ", statePtr, ", eventAny ", star(g, anypbPkg, "Any"), ") error {")
		emitDecode(g, "event", "eventAny", h.Message, "")
		g.P("return h.", h.MethodName, "(projection, event)")
		g.P("})")
	}
	g.P("dispatch.Finish(h.Finish)")
	g.P("return dispatch")
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterProjector"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

// emitSnapshotLoader registers the rebuilder's snapshot loader. A snapshot
// carries the component's own state message, so the loader unmarshals it into
// the rebuilding state — generic, no business method needed.
func emitSnapshotLoader(g *protogen.GeneratedFile, state *protogen.Message) {
	statePtr := "*" + g.QualifiedGoIdent(state.GoIdent)
	g.P("rebuilder.WithSnapshot(func(state ", statePtr, ", payload ", star(g, anypbPkg, "Any"), ") error {")
	g.P("return payload.UnmarshalTo(state)")
	g.P("})")
}

// emitDecode writes the typed-message decode guard shared by every handler
// thunk: declare the message, UnmarshalTo it, and code a decode failure as
// AnyDecodeError (a malformed payload is an invalid argument). ret is the
// values returned before the error on failure — "nil, nil, " for the saga's
// three-result handler, "nil, " for a two-result handler, "" when the only
// result is the error.
func emitDecode(g *protogen.GeneratedFile, name, anyVar string, m *protogen.Message, ret string) {
	g.P(name, " := &", g.QualifiedGoIdent(m.GoIdent), "{}")
	g.P("if err := ", anyVar, ".UnmarshalTo(", name, "); err != nil { return ", ret, ident(g, angzarrPkg, "AnyDecodeError"), "(", anyVar, ".TypeUrl, err) }")
}

// emitAppliers registers each event applier on the rebuilder: decode the
// payload into the typed event and fold it into state. Identical for
// aggregates and process managers — both rebuild state from their own events —
// so the two emitters share it.
func emitAppliers(g *protogen.GeneratedFile, s *Service, statePtr string) {
	for _, a := range s.Appliers {
		g.P("rebuilder.Apply(", quoteFQ(a.Message), ", func(state ", statePtr, ", payload ", star(g, anypbPkg, "Any"), ") error {")
		g.P("event := &", g.QualifiedGoIdent(a.Message.GoIdent), "{}")
		g.P("if err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("h.", a.MethodName, "(state, event)")
		g.P("return nil")
		g.P("})")
	}
}

// emitRegister writes the Register<Component> convenience that hides the
// per-kind registration split (free function vs. method) behind one call.
func emitRegister(g *protogen.GeneratedFile, s *Service, body func()) {
	name := s.GoName
	g.P("// Register", name, " registers a ", name, "Handler with the router.")
	g.P("func Register", name, "(r *", ident(g, angzarrPkg, "Router"), ", h ", name, "Handler) error {")
	body()
	g.P("}")
	g.P()
}

func quote(s string) string { return fmt.Sprintf("%q", s) }

// fqName is a message's fully-qualified proto name — the dispatch key the
// runtime matches on. Short names never match, so the FQ name is the contract.
// Every emitter keys its dispatch table on this.
func fqName(m *protogen.Message) string { return string(m.Desc.FullName()) }

// quoteFQ quotes fqName for the emitters that share quote (Go, Java, C#).
func quoteFQ(m *protogen.Message) string { return quote(fqName(m)) }
