package codegen

// Go emitter: for each declared component it emits, into Go,
//   - a STRICT handler interface (one typed method per declared rpc — a
//     missing handler is a compile error, never a silent no-op)
//   - a New<Component>Dispatch constructor that populates the engine's
//     dispatch table with unmarshal thunks calling the typed methods
//
// Generated code contains no dispatch logic and no gRPC — it is a thin
// table population over the angzarr-client-go engine, and the envelope
// stays google.protobuf.Any end to end.

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	angzarrPkg = protogen.GoImportPath("github.com/benjaminabbitt/angzarr/client/go")
	angzarrPb  = protogen.GoImportPath("github.com/benjaminabbitt/angzarr/client/go/proto/angzarr_client/proto/angzarr/v1")
	anypbPkg   = protogen.GoImportPath("google.golang.org/protobuf/types/known/anypb")
)

type goEmitter struct{}

func (goEmitter) Lang() string   { return "go" }
func (goEmitter) Suffix() string { return "_angzarr.pb.go" }

func (e goEmitter) EmitFile(g *protogen.GeneratedFile, file *protogen.File, services []*Service) error {
	g.P("// Code generated by angzarr codegen go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	for _, s := range services {
		var err error
		switch s.Component.Kind {
		case KindSaga:
			err = e.emitSaga(g, s)
		case KindAggregate:
			err = e.emitAggregate(g, s)
		case KindProcessManager:
			err = e.emitPM(g, s)
		case KindProjector:
			err = e.emitProjector(g, s)
		default:
			err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// idents used across emitters
func ident(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return g.QualifiedGoIdent(pkg.Ident(name))
}

func (goEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	name := s.Proto.GoName
	component := s.Component
	dests := "*" + ident(g, angzarrPkg, "Destinations")
	cmdBook := "*" + ident(g, angzarrPb, "CommandBook")
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " saga.")
	g.P("// Every declared rpc must be implemented — a missing handler is a")
	g.P("// compile error, never a silent no-op.")
	g.P("type ", name, "Handler interface {")
	for _, h := range s.Handlers {
		g.P("\t", h.Method.GoName, "(event *", g.QualifiedGoIdent(h.Method.Input.GoIdent), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error)")
	}
	for _, r := range s.Rejections {
		g.P("\t", r.Method.GoName, "(n ", notif, ", rejection ", rejn, ") ([]", evtBook, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine saga table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "SagaDispatch"), " {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewSagaDispatch"), "(", quote(string(s.Proto.Desc.Name())), ", ", quote(component.InputDomain), ", ", quote(component.OutputDomain), ").")
	for i, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(string(h.Method.Input.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Method.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.Method.GoName, "(event, dests)")
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.Method.GoName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func (goEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	name := s.Proto.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	bizResp := "*" + ident(g, angzarrPb, "BusinessResponse")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")
	cctx := ident(g, angzarrPkg, "CommandContext")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " aggregate.")
	g.P("type ", name, "Handler interface {")
	for _, h := range s.Handlers {
		g.P("\t", h.Method.GoName, "(cmd *", g.QualifiedGoIdent(h.Method.Input.GoIdent), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error)")
	}
	for _, m := range s.Appliers {
		g.P("\t", m.GoName, "(state ", statePtr, ", event *", g.QualifiedGoIdent(m.Input.GoIdent), ")")
	}
	for _, r := range s.Rejections {
		g.P("\t", r.Method.GoName, "(n ", notif, ", rejection ", rejn, ", state ", statePtr, ", cctx ", cctx, ") (", bizResp, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine aggregate table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "AggregateDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	for _, m := range s.Appliers {
		g.P("\trebuilder.Apply(", quote(string(m.Input.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", m.GoName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewAggregateDispatch"), "(", quote(string(s.Proto.Desc.Name())), ", ", quote(component.InputDomain), ", rebuilder).")
	for i, h := range s.Handlers {
		g.P("\t\tOnCommand(", quote(string(h.Method.Input.Desc.FullName())), ", func(cmdAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error) {")
		g.P("\t\t\tcmd := &", g.QualifiedGoIdent(h.Method.Input.GoIdent), "{}")
		g.P("\t\t\tif err := cmdAny.UnmarshalTo(cmd); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(cmdAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.Method.GoName, "(cmd, state, cctx)")
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.Method.GoName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func (goEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	name := s.Proto.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	dests := "*" + ident(g, angzarrPkg, "Destinations")
	pmResp := "*" + ident(g, angzarrPb, "ProcessManagerHandleResponse")
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " process manager.")
	g.P("type ", name, "Handler interface {")
	for _, h := range s.Handlers {
		g.P("\t", h.Method.GoName, "(event *", g.QualifiedGoIdent(h.Method.Input.GoIdent), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error)")
	}
	for _, m := range s.Appliers {
		g.P("\t", m.GoName, "(state ", statePtr, ", event *", g.QualifiedGoIdent(m.Input.GoIdent), ")")
	}
	for _, r := range s.Rejections {
		g.P("\t", r.Method.GoName, "(n ", notif, ", rejection ", rejn, ", state ", statePtr, ") ([]", evtBook, ", ", notif, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine PM table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProcessManagerDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	for _, m := range s.Appliers {
		g.P("\trebuilder.Apply(", quote(string(m.Input.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", m.GoName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewProcessManagerDispatch"), "(", quote(string(s.Proto.Desc.Name())), ", ", quote(component.OutputDomain), ", rebuilder).")
	for i, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(h.Reacts.GetDomain()), ", ", quote(string(h.Method.Input.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Method.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.Method.GoName, "(event, state, dests)")
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.Method.GoName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func (goEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	name := s.Proto.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	projection := "*" + ident(g, angzarrPb, "Projection")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " projector.")
	g.P("type ", name, "Handler interface {")
	for _, h := range s.Handlers {
		g.P("\t", h.Method.GoName, "(projection ", statePtr, ", event *", g.QualifiedGoIdent(h.Method.Input.GoIdent), ") error")
	}
	g.P("\t// Finish packs the folded instance into the wire Projection.")
	g.P("\tFinish(projection ", statePtr, ", events ", evtBook, ") (", projection, ", error)")
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine projector table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProjectorDispatch"), "[", statePtr, "] {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewProjectorDispatch"), "(", quote(string(s.Proto.Desc.Name())), ", func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} }).")
	g.P("\t\tForDomains(", quote(component.InputDomain), ").")
	for _, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(string(h.Method.Input.Desc.FullName())), ", func(projection ", statePtr, ", eventAny *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Method.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.Method.GoName, "(projection, event)")
		g.P("\t\t}).")
	}
	g.P("\t\tFinish(h.Finish)")
	g.P("}")
	g.P()
	return nil
}

func quote(s string) string { return fmt.Sprintf("%q", s) }

// trailer continues the fluent chain when more registrations follow.
func trailer(i, n int, more bool) string {
	if i < n-1 || more {
		return "." // not last — keep chaining
	}
	return ""
}
