package codegen

// Go emitter. For each declared component it emits two files:
//
//   - the WIRING file (Suffix, e.g. *_angzarr.pb.go): a STRICT
//     <Component>Handler interface (one typed method per declared
//     command/event — a missing handler is a compile error, never a silent
//     no-op), a New<Component>Dispatch constructor that populates the
//     binding's dispatch table with unmarshal thunks calling the typed
//     methods, and a Register<Component> convenience hiding the per-kind
//     registration split. This file is regenerated wholesale every run.
//
//   - the SCAFFOLD file (ScaffoldSuffix, e.g. *_angzarr_handler.go): a stub
//     <Component> struct implementing the interface, one TODO method per
//     declared command/event. It is generated ONCE — the plugin skips it when
//     the file already exists — then owned and edited by the developer;
//     regeneration never overwrites it. A compile-time
//     `var _ <Component>Handler = <Component>{}` assertion means a command or
//     event added to the proto surfaces as a build error pointing the
//     developer at the new method to implement.
//
// Generated code contains no dispatch logic and no gRPC — it is a thin table
// population over the angzarr-router Go binding (ffirouter), and the envelope
// stays google.protobuf.Any end to end. An aggregate command handler that
// declares exactly one emitted event type returns that typed slice and the
// wiring builds the EventBook; otherwise it returns the raw EventBook escape
// hatch (multi-type emission, custom covers, snapshots).

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	angzarrPkg = protogen.GoImportPath("github.com/angzarr-io/angzarr-router/bindings/go")
	angzarrPb  = protogen.GoImportPath("github.com/angzarr-io/angzarr-router/bindings/go/gen/io/angzarr/v1")
	anypbPkg   = protogen.GoImportPath("google.golang.org/protobuf/types/known/anypb")
)

type goEmitter struct{}

func (goEmitter) Lang() string { return "go" }

func (goEmitter) WiringPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr.pb.go")
}

func (goEmitter) ScaffoldPath(file *protogen.File, s *Service) string {
	return componentFile(file, snake(s.GoName), "_angzarr_handler.go")
}

func (e goEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Code generated by angzarr codegen go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	switch s.Component.Kind {
	case KindSaga:
		return e.emitSaga(g, s)
	case KindAggregate:
		return e.emitAggregate(g, s)
	case KindProcessManager:
		return e.emitPM(g, s)
	case KindProjector:
		return e.emitProjector(g, s)
	default:
		return fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
}

// EmitScaffoldComponent writes the generate-once handler stub: a struct
// implementing the component's Handler interface, each method with a TODO body
// and a compile-time interface-satisfaction assertion.
func (e goEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Scaffolded ONCE by angzarr codegen go — this file is YOURS.")
	g.P("//")
	g.P("// Regeneration will NOT overwrite this file. It is your responsibility to")
	g.P("// keep the generated <Component>Handler interface implemented: when a")
	g.P("// command or event is added to the proto, the var _ assertion below fails")
	g.P("// the build until you add the new method here.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	methods, err := e.methods(g, s)
	if err != nil {
		return err
	}
	g.P("// ", s.GoName, " implements ", s.GoName, "Handler.")
	g.P("type ", s.GoName, " struct{}")
	g.P()
	g.P("var _ ", s.GoName, "Handler = ", s.GoName, "{}")
	g.P()
	for _, m := range methods {
		g.P("func (", s.GoName, ") ", m.name, m.params, m.results, " {")
		if m.results == "" {
			g.P("\t// TODO: implement ", s.GoName, ".", m.name)
		} else {
			g.P("\tpanic(", quote("TODO: implement "+s.GoName+"."+m.name), ")")
		}
		g.P("}")
		g.P()
	}
	return nil
}

// methodSig is one generated handler method's signature, rendered once and
// shared by the strict interface and the scaffold stub so the two never drift.
type methodSig struct {
	name    string
	params  string // includes the enclosing parentheses
	results string // includes a leading space, or "" for a no-result method
}

// methods returns every handler method for a component, in interface order.
func (e goEmitter) methods(g *protogen.GeneratedFile, s *Service) ([]methodSig, error) {
	switch s.Component.Kind {
	case KindSaga:
		return e.sagaMethods(g, s), nil
	case KindAggregate:
		return e.aggregateMethods(g, s), nil
	case KindProcessManager:
		return e.pmMethods(g, s), nil
	case KindProjector:
		return e.projectorMethods(g, s), nil
	default:
		return nil, fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
}

// emitInterface writes the strict <Name>Handler interface from the shared
// method signatures.
func emitInterface(g *protogen.GeneratedFile, name, doc string, methods []methodSig) {
	g.P("// ", name, "Handler is the strict business seam for the ", doc, ".")
	g.P("// Every declared command/event must be implemented — a missing handler is")
	g.P("// a compile error, never a silent no-op.")
	g.P("type ", name, "Handler interface {")
	for _, m := range methods {
		g.P("\t", m.name, m.params, m.results)
	}
	g.P("}")
	g.P()
}

// idents used across emitters
func ident(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return g.QualifiedGoIdent(pkg.Ident(name))
}

func star(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return "*" + ident(g, pkg, name)
}

func (goEmitter) sagaMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	dests := star(g, angzarrPkg, "Destinations")
	cmdBook := star(g, angzarrPb, "CommandBook")
	evtBook := star(g, angzarrPb, "EventBook")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", dests " + dests + ")",
			results: " ([]" + cmdBook + ", []" + evtBook + ", error)",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ")",
			results: " ([]" + evtBook + ", error)",
		})
	}
	return out
}

func (goEmitter) aggregateMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	bizResp := star(g, angzarrPb, "BusinessResponse")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	cctx := ident(g, angzarrPkg, "CommandContext")
	var out []methodSig
	for _, h := range s.Handlers {
		results := " (" + evtBook + ", error)"
		if h.TypedEmit() {
			results = " ([]*" + g.QualifiedGoIdent(h.Emits[0].GoIdent) + ", error)"
		}
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(cmd *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", state " + statePtr + ", cctx " + cctx + ")",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, methodSig{
			name:   a.MethodName,
			params: "(state " + statePtr + ", event *" + g.QualifiedGoIdent(a.Message.GoIdent) + ")",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ", state " + statePtr + ", cctx " + cctx + ")",
			results: " (" + bizResp + ", error)",
		})
	}
	return out
}

func (goEmitter) pmMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	dests := star(g, angzarrPkg, "Destinations")
	pmResp := star(g, angzarrPb, "ProcessManagerHandleResponse")
	evtBook := star(g, angzarrPb, "EventBook")
	notif := star(g, angzarrPb, "Notification")
	rejn := star(g, angzarrPb, "RejectionNotification")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ", state " + statePtr + ", dests " + dests + ")",
			results: " (" + pmResp + ", error)",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, methodSig{
			name:   a.MethodName,
			params: "(state " + statePtr + ", event *" + g.QualifiedGoIdent(a.Message.GoIdent) + ")",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, methodSig{
			name:    r.MethodName,
			params:  "(n " + notif + ", rejection " + rejn + ", state " + statePtr + ")",
			results: " ([]" + evtBook + ", " + notif + ", error)",
		})
	}
	return out
}

func (goEmitter) projectorMethods(g *protogen.GeneratedFile, s *Service) []methodSig {
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	projection := star(g, angzarrPb, "Projection")
	var out []methodSig
	for _, h := range s.Handlers {
		out = append(out, methodSig{
			name:    h.MethodName,
			params:  "(projection " + statePtr + ", event *" + g.QualifiedGoIdent(h.Message.GoIdent) + ")",
			results: " error",
		})
	}
	out = append(out, methodSig{
		name:    "Finish",
		params:  "(projection " + statePtr + ", events " + evtBook + ")",
		results: " (" + projection + ", error)",
	})
	return out
}

func (e goEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	dests := star(g, angzarrPkg, "Destinations")
	cmdBook := star(g, angzarrPb, "CommandBook")
	evtBook := star(g, angzarrPb, "EventBook")

	emitInterface(g, name, name+" saga", e.sagaMethods(g, s))
	g.P("// New", name, "Dispatch populates the saga table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "SagaDispatch"), " {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewSagaDispatch"), "(", quote(name), ", ", quote(component.InputDomain), ", ", quote(component.OutputDomain), ").")
	for i, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(string(h.Message.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Message.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.MethodName, "(event, dests)")
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.MethodName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn r.RegisterSaga(New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	evtBook := star(g, angzarrPb, "EventBook")
	evtPage := ident(g, angzarrPb, "EventPage")
	evtPageEvent := ident(g, angzarrPb, "EventPage_Event")
	cctx := ident(g, angzarrPkg, "CommandContext")

	emitInterface(g, name, name+" aggregate", e.aggregateMethods(g, s))
	g.P("// New", name, "Dispatch populates the aggregate table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "AggregateDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	emitSnapshotLoader(g, s.State)
	for _, a := range s.Appliers {
		g.P("\trebuilder.Apply(", quote(string(a.Message.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(a.Message.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", a.MethodName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewAggregateDispatch"), "(", quote(name), ", ", quote(component.InputDomain), ", rebuilder).")
	for i, h := range s.Handlers {
		g.P("\t\tOnCommand(", quote(string(h.Message.Desc.FullName())), ", func(cmdAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error) {")
		g.P("\t\t\tcmd := &", g.QualifiedGoIdent(h.Message.GoIdent), "{}")
		g.P("\t\t\tif err := cmdAny.UnmarshalTo(cmd); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(cmdAny.TypeUrl, err) }")
		if h.TypedEmit() {
			g.P("\t\t\tevents, err := h.", h.MethodName, "(cmd, state, cctx)")
			g.P("\t\t\tif err != nil { return nil, err }")
			g.P("\t\t\tpages := make([]*", evtPage, ", len(events))")
			g.P("\t\t\tfor i, ev := range events {")
			g.P("\t\t\t\tpayload, err := ", ident(g, angzarrPkg, "Pack"), "(ev)")
			g.P("\t\t\t\tif err != nil { return nil, err }")
			g.P("\t\t\t\tpages[i] = &", evtPage, "{Payload: &", evtPageEvent, "{Event: payload}}")
			g.P("\t\t\t}")
			g.P("\t\t\treturn &", ident(g, angzarrPb, "EventBook"), "{Pages: pages}, nil")
		} else {
			g.P("\t\t\treturn h.", h.MethodName, "(cmd, state, cctx)")
		}
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.MethodName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterAggregate"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)
	dests := star(g, angzarrPkg, "Destinations")
	pmResp := star(g, angzarrPb, "ProcessManagerHandleResponse")

	emitInterface(g, name, name+" process manager", e.pmMethods(g, s))
	g.P("// New", name, "Dispatch populates the PM table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProcessManagerDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} })")
	emitSnapshotLoader(g, s.State)
	for _, a := range s.Appliers {
		g.P("\trebuilder.Apply(", quote(string(a.Message.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(a.Message.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", a.MethodName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewProcessManagerDispatch"), "(", quote(name), ", ", quote(component.OutputDomain), ", rebuilder).")
	for i, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(h.SourceDomain), ", ", quote(string(h.Message.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Message.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.MethodName, "(event, state, dests)")
		g.P("\t\t})", trailer(i, len(s.Handlers), len(s.Rejections) > 0))
	}
	for i, r := range s.Rejections {
		g.P("\t\tOnRejected(", quote(r.Command), ", h.", r.MethodName, ")", trailer(i, len(s.Rejections), false))
	}
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterProcessManager"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

func (e goEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	name := s.GoName
	component := s.Component
	statePtr := "*" + g.QualifiedGoIdent(s.State.GoIdent)

	emitInterface(g, name, name+" projector", e.projectorMethods(g, s))
	g.P("// New", name, "Dispatch populates the projector table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProjectorDispatch"), "[", statePtr, "] {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewProjectorDispatch"), "(", quote(name), ", func() ", statePtr, " { return &", g.QualifiedGoIdent(s.State.GoIdent), "{} }).")
	g.P("\t\tForDomains(", quote(component.InputDomain), ").")
	for _, h := range s.Handlers {
		g.P("\t\tOnEvent(", quote(string(h.Message.Desc.FullName())), ", func(projection ", statePtr, ", eventAny *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(h.Message.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", h.MethodName, "(projection, event)")
		g.P("\t\t}).")
	}
	g.P("\t\tFinish(h.Finish)")
	g.P("}")
	g.P()
	emitRegister(g, s, func() {
		g.P("\treturn ", ident(g, angzarrPkg, "RegisterProjector"), "(r, New", name, "Dispatch(h))")
	})
	return nil
}

// emitSnapshotLoader registers the rebuilder's snapshot loader. A snapshot
// carries the component's own state message, so the loader unmarshals it into
// the rebuilding state — generic, no business method needed.
func emitSnapshotLoader(g *protogen.GeneratedFile, state *protogen.Message) {
	statePtr := "*" + g.QualifiedGoIdent(state.GoIdent)
	g.P("\trebuilder.WithSnapshot(func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
	g.P("\t\treturn payload.UnmarshalTo(state)")
	g.P("\t})")
}

// emitRegister writes the Register<Component> convenience that hides the
// per-kind registration split (free function vs. method) behind one call.
func emitRegister(g *protogen.GeneratedFile, s *Service, body func()) {
	name := s.GoName
	g.P("// Register", name, " registers a ", name, "Handler with the router.")
	g.P("func Register", name, "(r *", ident(g, angzarrPkg, "Router"), ", h ", name, "Handler) error {")
	body()
	g.P("}")
	g.P()
}

func quote(s string) string { return fmt.Sprintf("%q", s) }

// trailer continues the fluent chain when more registrations follow.
func trailer(i, n int, more bool) string {
	if i < n-1 || more {
		return "." // not last — keep chaining
	}
	return ""
}
