package codegen

// Java emitter. Java forbids multiple public top-level classes per file, and the
// conformance fixtures (a separate package) must import the handler types, so —
// unlike the Go/Python emitters' one-public-class-per-component shape — each
// proto file's components are emitted into ONE wiring file as a single public
// outer class (named <protofile>_angzarr) holding a public nested
// <Component>Handler interface, a new<Component>Dispatch factory, and a
// register<Component> convenience per component. Type references are emitted as
// fully-qualified names (no import management): framework/runtime types under
// io.angzarr / io.angzarr.router, and domain message types computed from the
// file's java options. The envelope stays google.protobuf.Any end to end; state
// is a protobuf Builder (protobuf-java is immutable) that appliers fold into.

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	jRouter       = "io.angzarr.router.Router"
	jAggDispatch  = "io.angzarr.router.AggregateDispatch"
	jSagaDispatch = "io.angzarr.router.SagaDispatch"
	jProjDispatch = "io.angzarr.router.ProjectorDispatch"
	jPmDispatch   = "io.angzarr.router.ProcessManagerDispatch"
	jRebuilder    = "io.angzarr.router.Rebuilder"
	jCctx         = "io.angzarr.router.CommandContext"
	jDestinations = "io.angzarr.router.Destinations"
	jPack         = "io.angzarr.router.Pack"
	jCoded        = "io.angzarr.router.CodedError"
	jSagaEmission = "io.angzarr.router.Thunks.SagaEmission"
	jPmRejection  = "io.angzarr.router.Thunks.PmRejection"
	jEventBook    = "io.angzarr.EventBook"
	jEventPage    = "io.angzarr.EventPage"
	jBusinessResp = "io.angzarr.BusinessResponse"
	jNotification = "io.angzarr.Notification"
	jRejNotif     = "io.angzarr.RejectionNotification"
	jProjection   = "io.angzarr.Projection"
	jPmResponse   = "io.angzarr.ProcessManagerHandleResponse"
	jAny          = "com.google.protobuf.Any"
	jList         = "java.util.List"
)

type javaEmitter struct{}

func (javaEmitter) Lang() string { return "java" }

// Java forbids multiple public top-level types per file, so each component is a
// public final class <Component>Angzarr (matching the filename) holding the
// nested <Component>Handler interface + static new/register methods.
func (javaEmitter) WiringPath(file *protogen.File, s *Service) string {
	return componentFile(file, s.GoName+"Angzarr", ".java")
}

func (javaEmitter) ScaffoldPath(file *protogen.File, s *Service) string {
	return componentFile(file, s.GoName, ".java")
}

func (e javaEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Code generated by angzarr codegen java. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", javaPackage(file), ";")
	g.P()
	g.P("@SuppressWarnings({\"unchecked\", \"all\"})")
	cls := s.GoName + "Angzarr"
	g.P("public final class ", cls, " {")
	g.P("  private ", cls, "() {}")
	g.P()
	var err error
	switch s.Component.Kind {
	case KindAggregate:
		err = e.emitAggregate(g, s)
	case KindSaga:
		err = e.emitSaga(g, s)
	case KindProjector:
		err = e.emitProjector(g, s)
	case KindProcessManager:
		err = e.emitPM(g, s)
	default:
		err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
	if err != nil {
		return err
	}
	g.P("}")
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e javaEmitter) emitInterface(g *protogen.GeneratedFile, s *Service, doc string) {
	g.P("  /** The strict business seam for the ", doc, ". Every declared")
	g.P("   * command/event must be implemented — a missing handler is a compile error. */")
	g.P("  public interface ", s.GoName, "Handler {")
	for _, m := range e.methods(s) {
		g.P("    ", m.results, " ", m.name, "(", m.params, ")", m.throws, ";")
	}
	g.P("  }")
	g.P()
}

// methodSig is one handler method, shared by the interface and (future) scaffold.
type javaMethod struct {
	name    string
	params  string
	results string // "void" or a type
	throws  string // " throws Exception" or ""
}

func (e javaEmitter) methods(s *Service) []javaMethod {
	switch s.Component.Kind {
	case KindAggregate:
		return e.aggregateMethods(s)
	case KindSaga:
		return e.sagaMethods(s)
	case KindProjector:
		return e.projectorMethods(s)
	case KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e javaEmitter) aggregateMethods(s *Service) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		results := jEventBook
		if h.TypedEmit() {
			results = jList + "<" + javaType(h.Emits[0]) + ">"
		}
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " cmd, " + state + " state, " + jCctx + " cctx",
			results: results,
			throws:  " throws Exception",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, javaMethod{
			name:    lowerFirst(a.MethodName),
			params:  state + " state, " + javaType(a.Message) + " event",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection, " + state + " state, " + jCctx + " cctx",
			results: jBusinessResp,
			throws:  " throws Exception",
		})
	}
	return out
}

func (e javaEmitter) sagaMethods(s *Service) []javaMethod {
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " event, " + jDestinations + " dests",
			results: jSagaEmission,
			throws:  " throws Exception",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection",
			results: jList + "<" + jEventBook + ">",
			throws:  " throws Exception",
		})
	}
	return out
}

func (e javaEmitter) projectorMethods(s *Service) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  state + " projection, " + javaType(h.Message) + " event",
			results: "void",
			throws:  " throws Exception",
		})
	}
	out = append(out, javaMethod{
		name:    "finish",
		params:  state + " projection, " + jEventBook + " events",
		results: jProjection,
		throws:  " throws Exception",
	})
	return out
}

func (e javaEmitter) pmMethods(s *Service) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " event, " + state + " state, " + jDestinations + " dests",
			results: jPmResponse,
			throws:  " throws Exception",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, javaMethod{
			name:    lowerFirst(a.MethodName),
			params:  state + " state, " + javaType(a.Message) + " event",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection, " + state + " state",
			results: jPmRejection,
			throws:  " throws Exception",
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e javaEmitter) emitAggregate(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" aggregate")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the aggregate table from the proto declaration. */")
	g.P("  public static ", jAggDispatch, " new", s.GoName, "Dispatch(", s.GoName, "Handler h) {")
	g.P("    ", jRebuilder, " rebuilder = new ", jRebuilder, "(", javaType(s.State), "::newBuilder);")
	g.P("    rebuilder.withSnapshot((state, payload) -> ((", state, ") state).mergeFrom(payload.getValue()));")
	for _, a := range s.Appliers {
		g.P("    rebuilder.apply(", quote(a.fqType()), ", (state, payload) ->")
		g.P("        h.", lowerFirst(a.MethodName), "((", state, ") state, ", javaType(a.Message), ".parseFrom(payload.getValue())));")
	}
	g.P("    return new ", jAggDispatch, "(", quote(s.GoName), ", ", quote(s.Component.InputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("        .onCommand(", quote(string(h.Message.Desc.FullName())), ", (cmdAny, state, cctx) -> {")
		g.P("          ", javaType(h.Message), " cmd = ", parseAny(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("          ", jList, "<", javaType(h.Emits[0]), "> events = h.", lowerFirst(h.MethodName), "(cmd, (", state, ") state, cctx);")
			g.P("          ", jEventBook, ".Builder book = ", jEventBook, ".newBuilder();")
			g.P("          for (", javaType(h.Emits[0]), " ev : events) {")
			g.P("            book.addPages(", jEventPage, ".newBuilder().setEvent(", jPack, ".pack(ev)));")
			g.P("          }")
			g.P("          return book.build();")
		} else {
			g.P("          return h.", lowerFirst(h.MethodName), "(cmd, (", state, ") state, cctx);")
		}
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Command), ", (n, rejection, state, cctx) ->")
		g.P("            h.", lowerFirst(r.MethodName), "(n, rejection, (", state, ") state, cctx))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerAggregate")
	return nil
}

func (e javaEmitter) emitSaga(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" saga")
	g.P("  /** Populates the saga table from the proto declaration. */")
	g.P("  public static ", jSagaDispatch, " new", s.GoName, "Dispatch(", s.GoName, "Handler h) {")
	g.P("    return new ", jSagaDispatch, "(", quote(s.GoName), ", ", quote(s.Component.InputDomain), ", ", jList, ".of(", quote(s.Component.OutputDomain), "))")
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quote(string(h.Message.Desc.FullName())), ", (eventAny, dests) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          return h.", lowerFirst(h.MethodName), "(event, dests);")
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Command), ", (n, rejection) -> h.", lowerFirst(r.MethodName), "(n, rejection))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerSaga")
	return nil
}

func (e javaEmitter) emitProjector(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" projector")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the projector table from the proto declaration. */")
	g.P("  public static ", jProjDispatch, " new", s.GoName, "Dispatch(", s.GoName, "Handler h) {")
	g.P("    return new ", jProjDispatch, "(", quote(s.GoName), ", ", javaType(s.State), "::newBuilder)")
	g.P("        .forDomains(", quote(s.Component.InputDomain), ")")
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quote(string(h.Message.Desc.FullName())), ", (projection, eventAny) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          h.", lowerFirst(h.MethodName), "((", state, ") projection, event);")
		g.P("        })")
	}
	g.P("        .finish((projection, events) -> h.finish((", state, ") projection, events));")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerProjector")
	return nil
}

func (e javaEmitter) emitPM(g *protogen.GeneratedFile, s *Service) error {
	e.emitInterface(g, s, s.GoName+" process manager")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the PM table from the proto declaration. */")
	g.P("  public static ", jPmDispatch, " new", s.GoName, "Dispatch(", s.GoName, "Handler h) {")
	g.P("    ", jRebuilder, " rebuilder = new ", jRebuilder, "(", javaType(s.State), "::newBuilder);")
	g.P("    rebuilder.withSnapshot((state, payload) -> ((", state, ") state).mergeFrom(payload.getValue()));")
	for _, a := range s.Appliers {
		g.P("    rebuilder.apply(", quote(a.fqType()), ", (state, payload) ->")
		g.P("        h.", lowerFirst(a.MethodName), "((", state, ") state, ", javaType(a.Message), ".parseFrom(payload.getValue())));")
	}
	g.P("    return new ", jPmDispatch, "(", quote(s.GoName), ", ", quote(s.Component.OutputDomain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quote(h.SourceDomain), ", ", quote(string(h.Message.Desc.FullName())), ", (eventAny, state, dests) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          return h.", lowerFirst(h.MethodName), "(event, (", state, ") state, dests);")
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Command), ", (n, rejection, state) ->")
		g.P("            h.", lowerFirst(r.MethodName), "(n, rejection, (", state, ") state))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerProcessManager")
	return nil
}

func (e javaEmitter) emitRegister(g *protogen.GeneratedFile, s *Service, routerMethod string) {
	g.P("  /** Registers a ", s.GoName, "Handler with the router. */")
	g.P("  public static void register", s.GoName, "(", jRouter, " r, ", s.GoName, "Handler h) {")
	g.P("    r.", routerMethod, "(new", s.GoName, "Dispatch(h));")
	g.P("  }")
	g.P()
}

// EmitScaffoldComponent writes the generate-once developer stub: a public class
// <Component> implementing the component's Handler interface.
func (e javaEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Service) error {
	g.P("// Scaffolded ONCE by angzarr codegen java — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interface")
	g.P("// implemented as commands/events are added to the proto.")
	g.P()
	g.P("package ", javaPackage(file), ";")
	g.P()
	g.P("/** Implement ", s.GoName, "Handler here. */")
	g.P("public final class ", s.GoName, " implements ", s.GoName, "Angzarr.", s.GoName, "Handler {")
	for _, m := range e.methods(s) {
		g.P("  @Override public ", m.results, " ", m.name, "(", m.params, ")", m.throws, " {")
		if m.results == "void" {
			g.P("    // TODO: implement ", s.GoName, ".", m.name)
		} else {
			g.P("    throw new UnsupportedOperationException(", quote("TODO: implement "+s.GoName+"."+m.name), ");")
		}
		g.P("  }")
	}
	g.P("}")
	return nil
}

// --- Java naming helpers ------------------------------------------------------

func (a Applier) fqType() string { return string(a.Message.Desc.FullName()) }

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// parseAny renders the parse of an Any payload into the typed message, wrapping a
// decode failure as a coded ANY_DECODE_FAILED (a malformed payload is an invalid
// argument). Emitted inline as an immediately-invoked helper via a ternary is
// awkward in Java, so the parse is a guarded expression using a static helper on
// the message type plus a catch in a small lambda is overkill — instead the
// generated handler bodies wrap parse in a try/catch is verbose; we keep it
// simple: parseFrom throws and the trampoline codes it, but typed command/event
// parse failures should be ANY_DECODE_FAILED, so we route through CodedError.
func parseAny(m *protogen.Message, anyVar string) string {
	// io.angzarr.router.CodedError.parse(<Type>.parser(), anyVar) — a static
	// helper that maps InvalidProtocolBufferException to anyDecodeError.
	return jCoded + ".parse(" + javaType(m) + ".parser(), " + anyVar + ")"
}

// javaPackage resolves a file's Java package: the java_package option, else the
// proto package.
func javaPackage(file *protogen.File) string {
	fd := file.Desc
	if opts, ok := fd.Options().(*descriptorpb.FileOptions); ok && opts.JavaPackage != nil {
		return opts.GetJavaPackage()
	}
	return string(fd.Package())
}

// javaType computes the fully-qualified Java type name of a message: java
// package, then (unless java_multiple_files) the file's outer class, then the
// nested message path.
func javaType(m *protogen.Message) string {
	fd := m.Desc.ParentFile()
	opts, _ := fd.Options().(*descriptorpb.FileOptions)
	pkg := string(fd.Package())
	if opts != nil && opts.JavaPackage != nil {
		pkg = opts.GetJavaPackage()
	}
	nested := messageNestedName(m.Desc)
	if opts != nil && opts.GetJavaMultipleFiles() {
		return pkg + "." + nested
	}
	return pkg + "." + javaOuterClass(fd, opts) + "." + nested
}

// messageNestedName joins a message's name path within its file (Parent.Child).
func messageNestedName(md protoreflect.MessageDescriptor) string {
	parts := []string{string(md.Name())}
	for {
		parent, ok := md.Parent().(protoreflect.MessageDescriptor)
		if !ok {
			break
		}
		parts = append([]string{string(parent.Name())}, parts...)
		md = parent
	}
	return strings.Join(parts, ".")
}

// javaOuterClass derives the file's outer class name (java_outer_classname, else
// the PascalCase file base), applying protobuf's collision rule: if a top-level
// message/enum/service shares the name, append "OuterClass".
func javaOuterClass(fd protoreflect.FileDescriptor, opts *descriptorpb.FileOptions) string {
	if opts != nil && opts.JavaOuterClassname != nil {
		return opts.GetJavaOuterClassname()
	}
	base := path.Base(fd.Path())
	name := snakeToPascal(strings.TrimSuffix(base, ".proto"))
	if outerClassCollides(fd, name) {
		name += "OuterClass"
	}
	return name
}

func outerClassCollides(fd protoreflect.FileDescriptor, name string) bool {
	msgs := fd.Messages()
	for i := 0; i < msgs.Len(); i++ {
		if string(msgs.Get(i).Name()) == name {
			return true
		}
	}
	enums := fd.Enums()
	for i := 0; i < enums.Len(); i++ {
		if string(enums.Get(i).Name()) == name {
			return true
		}
	}
	svcs := fd.Services()
	for i := 0; i < svcs.Len(); i++ {
		if string(svcs.Get(i).Name()) == name {
			return true
		}
	}
	return false
}

func snakeToPascal(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' {
			upper = true
			continue
		}
		if upper {
			b.WriteString(strings.ToUpper(string(r)))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
