package codegen

// Java emitter. Each component's wiring is one file (<Component>Angzarr.java),
// the same one-file-per-component shape as every other emitter. What differs
// is the file's INTERNAL shape: Java forbids multiple public top-level types
// per file, and the conformance fixtures (a separate package) must import the
// handler types, so — unlike the Go/Python emitters' flat top-level
// declarations — everything nests inside a single public outer class
// <Component>Angzarr: a public nested <Component>Handler interface, a static
// new<Component>Dispatch factory, and a static register<Component>
// convenience. Type references are emitted as fully-qualified names (no import
// management): framework/runtime types under io.angzarr / io.angzarr.router,
// and domain message types computed from the file's java options. The
// envelope stays google.protobuf.Any end to end; state is a protobuf Builder
// (protobuf-java is immutable) that appliers fold into.

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	jRouter       = "io.angzarr.router.Router"
	jAggDispatch  = "io.angzarr.router.AggregateDispatch"
	jSagaDispatch = "io.angzarr.router.SagaDispatch"
	jProjDispatch = "io.angzarr.router.ProjectorDispatch"
	jPmDispatch   = "io.angzarr.router.ProcessManagerDispatch"
	jRebuilder    = "io.angzarr.router.Rebuilder"
	jCctx         = "io.angzarr.router.CommandContext"
	jDestinations = "io.angzarr.router.Destinations"
	jPack         = "io.angzarr.router.Pack"
	jCoded        = "io.angzarr.router.CodedError"
	jSagaEmission = "io.angzarr.router.Thunks.SagaEmission"
	jPmRejection  = "io.angzarr.router.Thunks.PmRejection"
	jCover        = "io.angzarr.Cover"
	jEventBook    = "io.angzarr.EventBook"
	jEventPage    = "io.angzarr.EventPage"
	jBusinessResp = "io.angzarr.BusinessResponse"
	jNotification = "io.angzarr.Notification"
	jRejNotif     = "io.angzarr.RejectionNotification"
	jProjection   = "io.angzarr.Projection"
	jPmResponse   = "io.angzarr.ProcessManagerHandleResponse"
	jAny          = "com.google.protobuf.Any"
	jList         = "java.util.List"
)

type javaEmitter struct{}

func (javaEmitter) Lang() string { return "java" }

// Java forbids multiple public top-level types per file, so each component is a
// public final class <Component>Angzarr (matching the filename) holding the
// nested <Component>Handler interface + static new/register methods.
func (javaEmitter) WiringPath(file *protogen.File, s *Component) string {
	return componentFile(file, s.BaseName+"Angzarr", ".java")
}

func (javaEmitter) ScaffoldPath(file *protogen.File, s *Component) string {
	return componentFile(file, s.StubName, ".java")
}

func (e javaEmitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *Component) error {
	g.P("// Code generated by angzarr codegen java. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", javaPackage(file), ";")
	g.P()
	g.P("@SuppressWarnings({\"unchecked\", \"all\"})")
	cls := s.BaseName + "Angzarr"
	g.P("public final class ", cls, " {")
	g.P("  private ", cls, "() {}")
	g.P()
	var err error
	switch s.Component.Kind {
	case KindAggregate:
		err = e.emitAggregate(g, s)
	case KindSaga:
		err = e.emitSaga(g, s)
	case KindProjector:
		err = e.emitProjector(g, s)
	case KindProcessManager:
		err = e.emitPM(g, s)
	default:
		err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
	if err != nil {
		return err
	}
	g.P("}")
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e javaEmitter) emitInterface(g *protogen.GeneratedFile, s *Component, doc string) {
	g.P("  /** The strict business seam for the ", doc, ". Every declared")
	g.P("   * command/event must be implemented — a missing handler is a compile error. */")
	g.P("  public interface ", s.BaseName, "Handler {")
	for _, m := range e.methods(s) {
		g.P("    ", m.results, " ", m.name, "(", m.params, ")", m.throws, ";")
	}
	g.P("  }")
	g.P()
}

// methodSig is one handler method, shared by the interface and the scaffold stub.
type javaMethod struct {
	name    string
	params  string
	results string // "void" or a type
	throws  string // " throws Exception" or ""
}

func (e javaEmitter) methods(s *Component) []javaMethod {
	switch s.Component.Kind {
	case KindAggregate:
		return e.aggregateMethods(s)
	case KindSaga:
		return e.sagaMethods(s)
	case KindProjector:
		return e.projectorMethods(s)
	case KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e javaEmitter) aggregateMethods(s *Component) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		results := jEventBook
		if h.TypedEmit() {
			results = jList + "<" + javaType(h.Emits[0]) + ">"
		}
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " cmd, " + state + " state, " + jCctx + " cctx",
			results: results,
			throws:  " throws Exception",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, javaMethod{
			name:    lowerFirst(a.MethodName),
			params:  state + " state, " + javaType(a.Message) + " event",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection, " + state + " state, " + jCctx + " cctx",
			results: jBusinessResp,
			throws:  " throws Exception",
		})
	}
	return out
}

func (e javaEmitter) sagaMethods(s *Component) []javaMethod {
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " event, " + jDestinations + " dests, " + jCover + " sourceCover",
			results: jSagaEmission,
			throws:  " throws Exception",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection",
			results: jList + "<" + jEventBook + ">",
			throws:  " throws Exception",
		})
	}
	return out
}

func (e javaEmitter) projectorMethods(s *Component) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  state + " projection, " + javaType(h.Message) + " event",
			results: "void",
			throws:  " throws Exception",
		})
	}
	out = append(out, javaMethod{
		name:    lowerFirst(projectorFinishMethod),
		params:  state + " projection, " + jEventBook + " events",
		results: jProjection,
		throws:  " throws Exception",
	})
	return out
}

func (e javaEmitter) pmMethods(s *Component) []javaMethod {
	state := javaType(s.State) + ".Builder"
	var out []javaMethod
	for _, h := range s.Handlers {
		out = append(out, javaMethod{
			name:    lowerFirst(h.MethodName),
			params:  javaType(h.Message) + " event, " + state + " state, " + jDestinations + " dests",
			results: jPmResponse,
			throws:  " throws Exception",
		})
	}
	for _, a := range s.Appliers {
		out = append(out, javaMethod{
			name:    lowerFirst(a.MethodName),
			params:  state + " state, " + javaType(a.Message) + " event",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, javaMethod{
			name:    lowerFirst(r.MethodName),
			params:  jNotification + " n, " + jRejNotif + " rejection, " + state + " state",
			results: jPmRejection,
			throws:  " throws Exception",
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e javaEmitter) emitAggregate(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" aggregate")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the aggregate table from the proto declaration. */")
	g.P("  public static ", jAggDispatch, " new", s.BaseName, "Dispatch(", s.BaseName, "Handler h) {")
	g.P("    ", jRebuilder, " rebuilder = new ", jRebuilder, "(", javaType(s.State), "::newBuilder);")
	g.P("    rebuilder.withSnapshot((state, payload) -> ((", state, ") state).mergeFrom(payload.getValue()));")
	emitJavaAppliers(g, s, state)
	g.P("    return new ", jAggDispatch, "(", quote(s.BaseName), ", ", quote(s.Component.Domain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("        .onCommand(", quoteFQ(h.Message), ", (cmdAny, state, cctx) -> {")
		g.P("          ", javaType(h.Message), " cmd = ", parseAny(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("          ", jList, "<", javaType(h.Emits[0]), "> events = h.", lowerFirst(h.MethodName), "(cmd, (", state, ") state, cctx);")
			g.P("          ", jEventBook, ".Builder book = ", jEventBook, ".newBuilder();")
			g.P("          for (", javaType(h.Emits[0]), " ev : events) {")
			g.P("            book.addPages(", jEventPage, ".newBuilder().setEvent(", jPack, ".pack(ev)));")
			g.P("          }")
			g.P("          return book.build();")
		} else {
			g.P("          return h.", lowerFirst(h.MethodName), "(cmd, (", state, ") state, cctx);")
		}
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Key), ", (n, rejection, state, cctx) ->")
		g.P("            h.", lowerFirst(r.MethodName), "(n, rejection, (", state, ") state, cctx))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerAggregate")
	return nil
}

func (e javaEmitter) emitSaga(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" saga")
	g.P("  /** Populates the saga table from the proto declaration. */")
	g.P("  public static ", jSagaDispatch, " new", s.BaseName, "Dispatch(", s.BaseName, "Handler h) {")
	g.P("    return new ", jSagaDispatch, "(", quote(s.BaseName), ", ", quote(s.Component.InputDomain), ", ", jList, ".of(", quoteJoin(s.Component.OutputDomains, quote), "))")
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quoteFQ(h.Message), ", (eventAny, dests, sourceCover) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          return h.", lowerFirst(h.MethodName), "(event, dests, sourceCover);")
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Key), ", (n, rejection) -> h.", lowerFirst(r.MethodName), "(n, rejection))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerSaga")
	return nil
}

func (e javaEmitter) emitProjector(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" projector")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the projector table from the proto declaration. */")
	g.P("  public static ", jProjDispatch, " new", s.BaseName, "Dispatch(", s.BaseName, "Handler h) {")
	g.P("    return new ", jProjDispatch, "(", quote(s.BaseName), ", ", javaType(s.State), "::newBuilder)")
	// Domain filter (Component.ProjectorDomains); omitted when empty so the
	// runtime default, consume every domain, applies.
	if len(s.ProjectorDomains) > 0 {
		g.P("        .forDomains(", quoteJoin(s.ProjectorDomains, quote), ")")
	}
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quoteFQ(h.Message), ", (projection, eventAny) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          h.", lowerFirst(h.MethodName), "((", state, ") projection, event);")
		g.P("        })")
	}
	g.P("        .finish((projection, events) -> h.finish((", state, ") projection, events));")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerProjector")
	return nil
}

func (e javaEmitter) emitPM(g *protogen.GeneratedFile, s *Component) error {
	e.emitInterface(g, s, s.BaseName+" process manager")
	state := javaType(s.State) + ".Builder"
	g.P("  /** Populates the PM table from the proto declaration. */")
	g.P("  public static ", jPmDispatch, " new", s.BaseName, "Dispatch(", s.BaseName, "Handler h) {")
	g.P("    ", jRebuilder, " rebuilder = new ", jRebuilder, "(", javaType(s.State), "::newBuilder);")
	g.P("    rebuilder.withSnapshot((state, payload) -> ((", state, ") state).mergeFrom(payload.getValue()));")
	emitJavaAppliers(g, s, state)
	g.P("    return new ", jPmDispatch, "(", quote(s.BaseName), ", ", quote(s.Component.Domain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("        .onEvent(", quote(h.SourceDomain), ", ", quoteFQ(h.Message), ", (eventAny, state, dests) -> {")
		g.P("          ", javaType(h.Message), " event = ", parseAny(h.Message, "eventAny"), ";")
		g.P("          return h.", lowerFirst(h.MethodName), "(event, (", state, ") state, dests);")
		g.P("        })")
	}
	for _, r := range s.Rejections {
		g.P("        .onRejected(", quote(r.Key), ", (n, rejection, state) ->")
		g.P("            h.", lowerFirst(r.MethodName), "(n, rejection, (", state, ") state))")
	}
	g.P("        ;")
	g.P("  }")
	g.P()
	e.emitRegister(g, s, "registerProcessManager")
	return nil
}

// emitJavaAppliers registers each event applier on the rebuilder. Identical for
// aggregates and process managers (both rebuild their own state). state is the
// state Builder type the appliers fold into.
func emitJavaAppliers(g *protogen.GeneratedFile, s *Component, state string) {
	for _, a := range s.Appliers {
		g.P("    rebuilder.apply(", quoteFQ(a.Message), ", (state, payload) ->")
		g.P("        h.", lowerFirst(a.MethodName), "((", state, ") state, ", javaType(a.Message), ".parseFrom(payload.getValue())));")
	}
}

func (e javaEmitter) emitRegister(g *protogen.GeneratedFile, s *Component, routerMethod string) {
	g.P("  /** Registers a ", s.BaseName, "Handler with the router. */")
	g.P("  public static void register", s.BaseName, "(", jRouter, " r, ", s.BaseName, "Handler h) {")
	g.P("    r.", routerMethod, "(new", s.BaseName, "Dispatch(h));")
	g.P("  }")
	g.P()
}

// EmitScaffoldComponent writes the generate-once developer stub: a public class
// <Component> implementing the component's Handler interface.
func (e javaEmitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *Component) error {
	g.P("// Scaffolded ONCE by angzarr codegen java — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interface")
	g.P("// implemented as commands/events are added to the proto.")
	g.P()
	g.P("package ", javaPackage(file), ";")
	g.P()
	g.P("/** Implement ", s.BaseName, "Handler here. */")
	g.P("public final class ", s.StubName, " implements ", s.BaseName, "Angzarr.", s.BaseName, "Handler {")
	for _, m := range e.methods(s) {
		g.P("  @Override public ", m.results, " ", m.name, "(", m.params, ")", m.throws, " {")
		if m.results == "void" {
			g.P("    // TODO: implement ", s.StubName, ".", m.name)
		} else {
			g.P("    throw new UnsupportedOperationException(", quote("TODO: implement "+s.StubName+"."+m.name), ");")
		}
		g.P("  }")
	}
	g.P("}")
	return nil
}

// --- Java naming helpers ------------------------------------------------------

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// parseAny renders the parse of an Any payload into the typed message as a
// single expression, not a try/catch statement — Java handler bodies are
// generated as one expression each (see EmitComponent), so parseAny must be an
// expression too. Invariant: a decode failure must surface as coded
// ANY_DECODE_FAILED, not a raw InvalidProtocolBufferException, so the
// generated expression always routes through CodedError.parse rather than the
// message type's own parseFrom.
func parseAny(m *protogen.Message, anyVar string) string {
	// io.angzarr.router.CodedError.parse(<Type>.parser(), anyVar) — a static
	// helper that maps InvalidProtocolBufferException to anyDecodeError.
	return jCoded + ".parse(" + javaType(m) + ".parser(), " + anyVar + ")"
}

// javaPackage resolves a file's Java package: the java_package option, else the
// proto package.
func javaPackage(file *protogen.File) string {
	fd := file.Desc
	if opts, ok := fd.Options().(*descriptorpb.FileOptions); ok && opts.JavaPackage != nil {
		return opts.GetJavaPackage()
	}
	return string(fd.Package())
}

// javaType computes the fully-qualified Java type name of a message: java
// package, then (unless java_multiple_files) the file's outer class, then the
// nested message path.
func javaType(m *protogen.Message) string {
	fd := m.Desc.ParentFile()
	opts, _ := fd.Options().(*descriptorpb.FileOptions)
	pkg := string(fd.Package())
	if opts != nil && opts.JavaPackage != nil {
		pkg = opts.GetJavaPackage()
	}
	nested := messageNestedName(m.Desc)
	if opts != nil && opts.GetJavaMultipleFiles() {
		return pkg + "." + nested
	}
	return pkg + "." + javaOuterClass(fd, opts) + "." + nested
}

// messageNestedName joins a message's name path within its file (Parent.Child).
func messageNestedName(md protoreflect.MessageDescriptor) string {
	return strings.Join(nestedNames(md), ".")
}

// javaOuterClass derives the file's outer class name (java_outer_classname, else
// the PascalCase file base), applying protobuf's collision rule: if a top-level
// message/enum/service shares the name, append "OuterClass".
func javaOuterClass(fd protoreflect.FileDescriptor, opts *descriptorpb.FileOptions) string {
	if opts != nil && opts.JavaOuterClassname != nil {
		return opts.GetJavaOuterClassname()
	}
	base := path.Base(fd.Path())
	name := snakeToPascal(strings.TrimSuffix(base, ".proto"))
	if outerClassCollides(fd, name) {
		name += "OuterClass"
	}
	return name
}

func outerClassCollides(fd protoreflect.FileDescriptor, name string) bool {
	msgs := fd.Messages()
	for i := 0; i < msgs.Len(); i++ {
		if string(msgs.Get(i).Name()) == name {
			return true
		}
	}
	enums := fd.Enums()
	for i := 0; i < enums.Len(); i++ {
		if string(enums.Get(i).Name()) == name {
			return true
		}
	}
	svcs := fd.Services()
	for i := 0; i < svcs.Len(); i++ {
		if string(svcs.Get(i).Name()) == name {
			return true
		}
	}
	return false
}

// snakeToPascal is protoc's UnderscoresToCamelCase with the first letter
// capitalised: a letter after an underscore, digit or other non-alphanumeric
// is upper-cased, the non-alphanumerics are dropped, digits are kept.
func snakeToPascal(s string) string {
	var b strings.Builder
	capNext := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
			if capNext {
				r -= 'a' - 'A'
			}
			b.WriteRune(r)
			capNext = false
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
			capNext = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			capNext = true
		default:
			capNext = true
		}
	}
	return b.String()
}
