package csharp

// C# emitter. Like the Java emitter, each component's wiring is one file
// (<Component>Angzarr.cs), and — because the conformance fixtures (a separate
// namespace) must import the handler types — everything nests inside a single
// public static outer class <Component>Angzarr: a public nested
// <Component>Handler interface, a static New<Component>Dispatch factory, and a
// static Register<Component> convenience. Type references are fully qualified
// (no using management): framework message types under the Angzarr namespace,
// runtime types under Angzarr.Router, and domain message types computed from
// the file's csharp_namespace (or the PascalCase package). Unlike Java,
// Google.Protobuf messages are MUTABLE — state is the message itself (no
// Builder), the factory is () => new <State>(), and appliers fold via
// property setters / MergeFrom.

import (
	"fmt"
	"strings"

	"github.com/angzarr-io/angzarr-cli/codegen"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Runtime (binding) + framework (message) type names, fully qualified.
const (
	csRouter       = "Angzarr.Router.Router"
	csAggDispatch  = "Angzarr.Router.AggregateDispatch"
	csSagaDispatch = "Angzarr.Router.SagaDispatch"
	csProjDispatch = "Angzarr.Router.ProjectorDispatch"
	csPmDispatch   = "Angzarr.Router.ProcessManagerDispatch"
	csRebuilder    = "Angzarr.Router.Rebuilder"
	csCctx         = "Angzarr.Router.CommandContext"
	csDestinations = "Angzarr.Router.Destinations"
	csPack         = "Angzarr.Router.Pack"
	csCoded        = "Angzarr.Router.CodedError"
	csSagaEmission = "Angzarr.Router.SagaEmission"
	csPageContext  = "Angzarr.Router.PageContext"
	csFactRecord   = "Angzarr.Router.FactRecord"
	csCompensate   = "Angzarr.Compensate"
	csCover        = "Angzarr.Cover"
	csEventBook    = "Angzarr.EventBook"
	csEventPage    = "Angzarr.EventPage"
	csBusinessResp = "Angzarr.BusinessResponse"
	csNotification = "Angzarr.Notification"
	csRejNotif     = "Angzarr.RejectionNotification"
	csProjection   = "Angzarr.Projection"
	csPmResponse   = "Angzarr.ProcessManagerHandleResponse"
	csList         = "System.Collections.Generic.IReadOnlyList"
)

// Emitter is the C# codegen.Emitter.
type Emitter struct{}

func (Emitter) Lang() string { return "csharp" }

// One public static class <Component>Angzarr per component (file matches the
// type), holding the nested <Component>Handler interface + New/Register methods.
func (Emitter) WiringPath(file *protogen.File, s *codegen.Component) string {
	return codegen.ComponentFile(file, s.BaseName+"Angzarr", ".cs")
}

func (Emitter) ScaffoldPath(file *protogen.File, s *codegen.Component) string {
	return codegen.ComponentFile(file, s.StubName, ".cs")
}

func (e Emitter) EmitComponent(g *protogen.GeneratedFile, file *protogen.File, s *codegen.Component) error {
	g.P("// <auto-generated/>")
	g.P("// Code generated by angzarr codegen csharp. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("namespace ", csNamespace(file), ";")
	g.P()
	g.P("public static class ", s.BaseName, "Angzarr")
	g.P("{")
	var err error
	switch s.Component.Kind {
	case codegen.KindAggregate:
		err = e.emitAggregate(g, s)
	case codegen.KindSaga:
		err = e.emitSaga(g, s)
	case codegen.KindProjector:
		err = e.emitProjector(g, s)
	case codegen.KindProcessManager:
		err = e.emitPM(g, s)
	default:
		err = fmt.Errorf("unsupported component kind %v", s.Component.Kind)
	}
	if err != nil {
		return err
	}
	g.P("}")
	return nil
}

// --- interface (the strict seam) ----------------------------------------------

func (e Emitter) emitInterface(g *protogen.GeneratedFile, s *codegen.Component, doc string) {
	g.P("    /// <summary>The strict business seam for the ", doc, ". Every declared")
	g.P("    /// command/event must be implemented — a missing handler is a compile error.</summary>")
	g.P("    public interface ", s.BaseName, "Handler")
	g.P("    {")
	for _, m := range e.methods(s) {
		g.P("        ", m.results, " ", m.name, "(", m.params, ");")
	}
	g.P("    }")
	g.P()
}

// csMethod is one handler method, shared by the interface and the scaffold.
type csMethod struct {
	name    string
	params  string
	results string // "void" or a type
}

func (e Emitter) methods(s *codegen.Component) []csMethod {
	switch s.Component.Kind {
	case codegen.KindAggregate:
		return e.aggregateMethods(s)
	case codegen.KindSaga:
		return e.sagaMethods(s)
	case codegen.KindProjector:
		return e.projectorMethods(s)
	case codegen.KindProcessManager:
		return e.pmMethods(s)
	}
	return nil
}

func (e Emitter) aggregateMethods(s *codegen.Component) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		results := csEventBook
		if h.TypedEmit() {
			results = csList + "<" + csType(h.Emits[0]) + ">"
		}
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " cmd, " + state + " state, " + csCctx + " cctx",
			results: results,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, csMethod{
			name:    a.MethodName,
			params:  state + " state, " + csType(a.Message) + " ev, " + csPageContext + " page",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, csMethod{
			name:    r.MethodName,
			params:  csNotification + " n, " + csRejNotif + " rejection, " + state + " state, " + csCctx + " cctx",
			results: csBusinessResp,
		})
	}
	for _, f := range s.Facts {
		out = append(out, csMethod{
			name:    f.MethodName,
			params:  csType(f.Message) + " fact, " + state + " state",
			results: csFactRecord + "?",
		})
	}
	for _, u := range s.Undos {
		out = append(out, csMethod{
			name:    u.MethodName,
			params:  csNotification + " n, " + csCompensate + " compensate, " + state + " state, " + csCctx + " cctx",
			results: csBusinessResp,
		})
	}
	return out
}

func (e Emitter) sagaMethods(s *codegen.Component) []csMethod {
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " ev, " + csDestinations + " dests, " + csPageContext + " source",
			results: csSagaEmission,
		})
	}
	return out
}

func (e Emitter) projectorMethods(s *codegen.Component) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  state + " projection, " + csType(h.Message) + " ev, " + csPageContext + " page",
			results: "void",
		})
	}
	out = append(out, csMethod{
		name:    codegen.ProjectorFinishMethod,
		params:  state + " projection, " + csEventBook + " events",
		results: csProjection,
	})
	return out
}

func (e Emitter) pmMethods(s *codegen.Component) []csMethod {
	state := csType(s.State)
	var out []csMethod
	for _, h := range s.Handlers {
		out = append(out, csMethod{
			name:    h.MethodName,
			params:  csType(h.Message) + " ev, " + state + " state, " + csDestinations + " dests, " + csCover + "? triggerCover",
			results: csPmResponse,
		})
	}
	for _, a := range s.Appliers {
		out = append(out, csMethod{
			name:    a.MethodName,
			params:  state + " state, " + csType(a.Message) + " ev, " + csPageContext + " page",
			results: "void",
		})
	}
	for _, r := range s.Rejections {
		out = append(out, csMethod{
			name:    r.MethodName,
			params:  csNotification + " n, " + csRejNotif + " rejection, " + state + " state",
			results: csPmResponse,
		})
	}
	return out
}

// --- wiring (dispatch table population) ---------------------------------------

func (e Emitter) emitAggregate(g *protogen.GeneratedFile, s *codegen.Component) error {
	e.emitInterface(g, s, s.BaseName+" aggregate")
	state := csType(s.State)
	g.P("    /// <summary>Populates the aggregate table from the proto declaration.</summary>")
	g.P("    public static ", csGeneric(csAggDispatch, state), " New", s.BaseName, "Dispatch(", s.BaseName, "Handler h)")
	g.P("    {")
	g.P("        var rebuilder = new ", csGeneric(csRebuilder, state), "(() => new ", state, "());")
	g.P("        rebuilder.WithSnapshot((state, payload) => Google.Protobuf.MessageExtensions.MergeFrom(state, payload.Value));")
	emitCsAppliers(g, s)
	g.P("        return new ", csGeneric(csAggDispatch, state), "(", codegen.Quote(s.BaseName), ", ", codegen.Quote(s.Component.Domain), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("            .OnCommand(", codegen.QuoteFQ(h.Message), ", (cmdAny, state, cctx) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " cmd = ", csParseAny(h.Message, "cmdAny"), ";")
		if h.TypedEmit() {
			g.P("                var events = h.", h.MethodName, "(cmd, state, cctx);")
			g.P("                var book = new ", csEventBook, "();")
			g.P("                foreach (var ev in events)")
			g.P("                {")
			g.P("                    book.Pages.Add(new ", csEventPage, " { Event = ", csPack, ".Wrap(ev) });")
			g.P("                }")
			g.P("                return book;")
		} else {
			g.P("                return h.", h.MethodName, "(cmd, state, cctx);")
		}
		g.P("            })")
	}
	for _, r := range s.Rejections {
		g.P("            .OnRejected(", codegen.Quote(r.Key), ", (n, rejection, state, cctx) =>")
		g.P("                h.", r.MethodName, "(n, rejection, state, cctx))")
	}
	for _, f := range s.Facts {
		g.P("            .OnFact(", codegen.QuoteFQ(f.Message), ", (factAny, state) =>")
		g.P("            {")
		g.P("                ", csType(f.Message), " fact = ", csParseAny(f.Message, "factAny"), ";")
		g.P("                return h.", f.MethodName, "(fact, state) ?? ", csFactRecord, ".AsReceived(factAny);")
		g.P("            })")
	}
	for _, u := range s.Undos {
		g.P("            .OnUndo(", codegen.Quote(u.Command), ", (n, compensate, state, cctx) =>")
		g.P("                h.", u.MethodName, "(n, compensate, state, cctx))")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterAggregate")
	return nil
}

func (e Emitter) emitSaga(g *protogen.GeneratedFile, s *codegen.Component) error {
	e.emitInterface(g, s, s.BaseName+" saga")
	g.P("    /// <summary>Populates the saga table from the proto declaration.</summary>")
	g.P("    public static ", csSagaDispatch, " New", s.BaseName, "Dispatch(", s.BaseName, "Handler h)")
	g.P("    {")
	g.P("        return new ", csSagaDispatch, "(", codegen.Quote(s.BaseName), ", ", codegen.Quote(s.Component.InputDomain), ", ", codegen.QuoteJoin(s.Component.OutputDomains, codegen.Quote), ")")
	for _, h := range s.Handlers {
		g.P("            .OnEventWithContext(", codegen.QuoteFQ(h.Message), ", (eventAny, dests, source) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                return h.", h.MethodName, "(ev, dests, source);")
		g.P("            })")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterSaga")
	return nil
}

func (e Emitter) emitProjector(g *protogen.GeneratedFile, s *codegen.Component) error {
	e.emitInterface(g, s, s.BaseName+" projector")
	state := csType(s.State)
	g.P("    /// <summary>Populates the projector table from the proto declaration.</summary>")
	g.P("    public static ", csGeneric(csProjDispatch, state), " New", s.BaseName, "Dispatch(", s.BaseName, "Handler h)")
	g.P("    {")
	g.P("        return new ", csGeneric(csProjDispatch, state), "(", codegen.Quote(s.BaseName), ", () => new ", state, "())")
	// Domain filter (Component.ProjectorDomains); omitted when empty so the
	// runtime default, consume every domain, applies.
	if len(s.ProjectorDomains) > 0 {
		g.P("            .ForDomains(", codegen.QuoteJoin(s.ProjectorDomains, codegen.Quote), ")")
	}
	for _, h := range s.Handlers {
		g.P("            .OnEvent(", codegen.QuoteFQ(h.Message), ", (projection, eventAny, page) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                h.", h.MethodName, "(projection, ev, page);")
		g.P("            })")
	}
	g.P("            .Finish((projection, events) => h.Finish(projection, events));")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterProjector")
	return nil
}

func (e Emitter) emitPM(g *protogen.GeneratedFile, s *codegen.Component) error {
	e.emitInterface(g, s, s.BaseName+" process manager")
	state := csType(s.State)
	g.P("    /// <summary>Populates the PM table from the proto declaration.</summary>")
	g.P("    public static ", csGeneric(csPmDispatch, state), " New", s.BaseName, "Dispatch(", s.BaseName, "Handler h)")
	g.P("    {")
	g.P("        var rebuilder = new ", csGeneric(csRebuilder, state), "(() => new ", state, "());")
	g.P("        rebuilder.WithSnapshot((state, payload) => Google.Protobuf.MessageExtensions.MergeFrom(state, payload.Value));")
	emitCsAppliers(g, s)
	g.P("        return new ", csGeneric(csPmDispatch, state), "(", codegen.Quote(s.BaseName), ", ", codegen.Quote(s.Component.Domain), ", ", csStringArray(s.Component.OutputDomains), ", rebuilder)")
	for _, h := range s.Handlers {
		g.P("            .OnEvent(", codegen.Quote(h.SourceDomain), ", ", codegen.QuoteFQ(h.Message), ", (eventAny, state, dests, triggerCover) =>")
		g.P("            {")
		g.P("                ", csType(h.Message), " ev = ", csParseAny(h.Message, "eventAny"), ";")
		g.P("                return h.", h.MethodName, "(ev, state, dests, triggerCover);")
		g.P("            })")
	}
	for _, r := range s.Rejections {
		g.P("            .OnRejectedResponse(", codegen.Quote(r.Key), ", (n, rejection, state) =>")
		g.P("                h.", r.MethodName, "(n, rejection, state))")
	}
	g.P("            ;")
	g.P("    }")
	g.P()
	e.emitRegister(g, s, "RegisterProcessManager")
	return nil
}

// emitCsAppliers registers each event applier on the rebuilder. Identical for
// aggregates and process managers (both rebuild their own state).
func emitCsAppliers(g *protogen.GeneratedFile, s *codegen.Component) {
	for _, a := range s.Appliers {
		g.P("        rebuilder.ApplyWithContext(", codegen.QuoteFQ(a.Message), ", (state, payload, page) =>")
		g.P("            h.", a.MethodName, "(state, ", csParse(a.Message, "payload.Value"), ", page));")
	}
}

func (e Emitter) emitRegister(g *protogen.GeneratedFile, s *codegen.Component, routerMethod string) {
	g.P("    /// <summary>Registers a ", s.BaseName, "Handler with the router.</summary>")
	g.P("    public static void Register", s.BaseName, "(", csRouter, " r, ", s.BaseName, "Handler h)")
	g.P("    {")
	g.P("        r.", routerMethod, "(New", s.BaseName, "Dispatch(h));")
	g.P("    }")
	g.P()
}

// EmitScaffoldComponent writes the generate-once developer stub: a public
// sealed class implementing the component's nested Handler interface.
func (e Emitter) EmitScaffoldComponent(g *protogen.GeneratedFile, file *protogen.File, s *codegen.Component) error {
	g.P("// Scaffolded ONCE by angzarr codegen csharp — this file is YOURS.")
	g.P("// Regeneration will NOT overwrite it; keep the generated Handler interface")
	g.P("// implemented as commands/events are added to the proto.")
	g.P()
	g.P("namespace ", csNamespace(file), ";")
	g.P()
	g.P("/// <summary>Implement ", s.BaseName, "Handler here.</summary>")
	g.P("public sealed class ", s.StubName, " : ", s.BaseName, "Angzarr.", s.BaseName, "Handler")
	g.P("{")
	for _, m := range e.methods(s) {
		g.P("    public ", m.results, " ", m.name, "(", m.params, ")")
		g.P("    {")
		if m.results == "void" {
			g.P("        // TODO: implement ", s.StubName, ".", m.name)
		} else {
			g.P("        throw new System.NotImplementedException(", codegen.Quote("TODO: implement "+s.StubName+"."+m.name), ");")
		}
		g.P("    }")
	}
	g.P("}")
	return nil
}

// --- C# naming helpers --------------------------------------------------------

// csParseAny renders the parse of an Any payload into the typed message, routing
// a decode failure through CodedError as ANY_DECODE_FAILED.
func csParseAny(m *protogen.Message, anyVar string) string {
	return csCoded + ".Parse(" + csType(m) + ".Parser, " + anyVar + ")"
}

// csParse parses a typed message directly from a ByteString (applier payloads).
func csParse(m *protogen.Message, bytesVar string) string {
	return csType(m) + ".Parser.ParseFrom(" + bytesVar + ")"
}

// csStringArray renders a string[] literal; an empty one has no element to
// infer the type from, so it is Array.Empty<string>().
func csStringArray(items []string) string {
	if len(items) == 0 {
		return "System.Array.Empty<string>()"
	}
	return "new[] { " + codegen.QuoteJoin(items, codegen.Quote) + " }"
}

// csGeneric renders a generic type reference, e.g. AggregateDispatch<Ns.State>.
func csGeneric(base, typeArg string) string {
	return base + "<" + typeArg + ">"
}

// csNamespace resolves a file's C# namespace: the csharp_namespace option, else
// each proto package segment PascalCased and joined with ".".
func csNamespace(file *protogen.File) string {
	return csNamespaceOf(file.Desc)
}

func csNamespaceOf(fd protoreflect.FileDescriptor) string {
	if opts, ok := fd.Options().(*descriptorpb.FileOptions); ok && opts.CsharpNamespace != nil {
		return opts.GetCsharpNamespace()
	}
	return pascalNamespace(string(fd.Package()))
}

// pascalNamespace PascalCases each dotted package segment (test.counter →
// Test.Counter), matching protoc's default C# namespace derivation.
func pascalNamespace(pkg string) string {
	if pkg == "" {
		return ""
	}
	parts := strings.Split(pkg, ".")
	for i, p := range parts {
		parts[i] = codegen.SnakeToPascal(p)
	}
	return strings.Join(parts, ".")
}

// csType computes the fully-qualified C# type name of a message: the file's C#
// namespace, then the nested message path joined by ".Types." (Google.Protobuf
// nests message types under a Types container).
func csType(m *protogen.Message) string {
	fd := m.Desc.ParentFile()
	ns := csNamespaceOf(fd)
	nested := csNestedName(m.Desc)
	if ns == "" {
		return nested
	}
	return ns + "." + nested
}

// csNestedName joins a message's name path within its file, with ".Types."
// between levels (Outer.Types.Inner).
func csNestedName(md protoreflect.MessageDescriptor) string {
	return strings.Join(codegen.NestedNames(md), ".Types.")
}
