# Code generated by angzarr codegen python. DO NOT EDIT.
# source: test/counter/counter.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from angzarr_client.proto.io.angzarr.v1 import process_manager_pb2 as _pm
from . import counter_pb2 as _counter

class AuditProcessManagerHandler(Protocol):
    """Strict business seam for the AuditProcessManager process_manager."""

    def increased(self, event: _counter.Increased, state: _counter.AuditProcessManagerState, dests: _az.Destinations, trigger_cover: Optional[_t.Cover]) -> _pm.ProcessManagerHandleResponse: ...
    def apply_increased(self, state: _counter.AuditProcessManagerState, event: _counter.Increased, ctx: _az.PageContext) -> None: ...
    def on_reserve_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _counter.AuditProcessManagerState) -> Optional[_pm.ProcessManagerHandleResponse]: ...

def new_audit_process_manager_dispatch(handler: AuditProcessManagerHandler) -> _az.ProcessManagerDispatch:
    rebuilder = _az.Rebuilder(lambda: _counter.AuditProcessManagerState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_increased(state, payload, ctx):
        event = _counter.Increased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_increased(state, event, ctx)
    rebuilder.apply_with_context("test.counter.Increased", _apply_apply_increased)
    dispatch = _az.ProcessManagerDispatch("AuditProcessManager", "audit-pm", rebuilder, targets=[])
    def _on_increased(event_any, state, dests, trigger_cover):
        event = _counter.Increased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.increased(event, state, dests, trigger_cover)
    dispatch.on_event_with_cover("counter", "test.counter.Increased", _on_increased)
    dispatch.on_rejected("test.counter.Reserve", handler.on_reserve_rejected)
    return dispatch

def register_audit_process_manager(router: _az.Router, handler: AuditProcessManagerHandler) -> None:
    router.register_process_manager(new_audit_process_manager_dispatch(handler))

