# Code generated by angzarr codegen python. DO NOT EDIT.
# source: test/counter/counter.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from angzarr_client.proto.io.angzarr.v1 import command_handler_pb2 as _ch
from . import counter_pb2 as _counter

class CounterAggregateHandler(Protocol):
    """Strict business seam for the CounterAggregate aggregate."""

    def increase_by(self, cmd: _counter.IncreaseBy, state: _counter.CounterState, cctx: _az.CommandContext) -> list[_counter.Increased]: ...
    def fail_hard(self, cmd: _counter.FailHard, state: _counter.CounterState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_increased(self, state: _counter.CounterState, event: _counter.Increased, ctx: _az.PageContext) -> None: ...
    def on_reserve_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _counter.CounterState, cctx: _az.CommandContext) -> Optional[_ch.BusinessResponse]: ...

def new_counter_aggregate_dispatch(handler: CounterAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _counter.CounterState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_increased(state, payload, ctx):
        event = _counter.Increased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_increased(state, event, ctx)
    rebuilder.apply_with_context("test.counter.Increased", _apply_apply_increased)
    dispatch = _az.AggregateDispatch("CounterAggregate", "counter", rebuilder)
    def _on_increase_by(cmd_any, state, cctx):
        cmd = _counter.IncreaseBy()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        events = handler.increase_by(cmd, state, cctx)
        book = _t.EventBook()
        for ev in events:
            book.pages.add().event.CopyFrom(_az.pack(ev))
        return book
    dispatch.on_command("test.counter.IncreaseBy", _on_increase_by)
    def _on_fail_hard(cmd_any, state, cctx):
        cmd = _counter.FailHard()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.fail_hard(cmd, state, cctx)
    dispatch.on_command("test.counter.FailHard", _on_fail_hard)
    dispatch.on_rejected("test.counter.Reserve", handler.on_reserve_rejected)
    return dispatch

def register_counter_aggregate(router: _az.Router, handler: CounterAggregateHandler) -> None:
    router.register_aggregate(new_counter_aggregate_dispatch(handler))

