# Code generated by angzarr codegen python. DO NOT EDIT.
# source: test/counter/counter.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import counter_pb2 as _counter

class CounterProjectorHandler(Protocol):
    """Strict business seam for the CounterProjector projector."""

    def increased(self, projection: _counter.CounterProjectorState, event: _counter.Increased, ctx: _az.PageContext) -> None: ...
    def finish(self, projection: _counter.CounterProjectorState, events: _t.EventBook) -> _t.Projection: ...

def new_counter_projector_dispatch(handler: CounterProjectorHandler) -> _az.ProjectorDispatch:
    dispatch = _az.ProjectorDispatch("CounterProjector", lambda: _counter.CounterProjectorState())
    dispatch.for_domains("counter")
    def _on_increased(projection, event_any, ctx):
        event = _counter.Increased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.increased(projection, event, ctx)
    dispatch.on_event_with_context("test.counter.Increased", _on_increased)
    dispatch.finish(handler.finish)
    return dispatch

def register_counter_projector(router: _az.Router, handler: CounterProjectorHandler) -> None:
    router.register_projector(new_counter_projector_dispatch(handler))

