# Code generated by angzarr codegen python. DO NOT EDIT.
# source: test/counter/counter.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import counter_pb2 as _counter

class OrderSagaHandler(Protocol):
    """Strict business seam for the OrderSaga saga."""

    def increased(self, event: _counter.Increased, dests: _az.Destinations, source: _az.PageContext) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_order_saga_dispatch(handler: OrderSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("OrderSaga", "order", targets=["inventory"])
    def _on_increased(event_any, dests, source):
        event = _counter.Increased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.increased(event, dests, source)
    dispatch.on_event_with_context("test.counter.Increased", _on_increased)
    return dispatch

def register_order_saga(router: _az.Router, handler: OrderSagaHandler) -> None:
    router.register_saga(new_order_saga_dispatch(handler))

