# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/buy_in.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from angzarr_client.proto.io.angzarr.v1 import process_manager_pb2 as _pm
from . import buy_in_pb2 as _buy_in
from . import player_pb2 as _player
from . import table_pb2 as _table

class BuyInProcessManagerHandler(Protocol):
    """Strict business seam for the BuyInProcessManager process_manager."""

    def funds_held(self, event: _player.FundsHeld, state: _buy_in.BuyInState, dests: _az.Destinations, trigger_cover: Optional[_t.Cover]) -> _pm.ProcessManagerHandleResponse: ...
    def funds_captured(self, event: _player.FundsCaptured, state: _buy_in.BuyInState, dests: _az.Destinations, trigger_cover: Optional[_t.Cover]) -> _pm.ProcessManagerHandleResponse: ...
    def seat_held(self, event: _table.SeatHeld, state: _buy_in.BuyInState, dests: _az.Destinations, trigger_cover: Optional[_t.Cover]) -> _pm.ProcessManagerHandleResponse: ...
    def player_seated(self, event: _table.PlayerSeated, state: _buy_in.BuyInState, dests: _az.Destinations, trigger_cover: Optional[_t.Cover]) -> _pm.ProcessManagerHandleResponse: ...
    def apply_buy_in_started(self, state: _buy_in.BuyInState, event: _buy_in.BuyInStarted, ctx: _az.PageContext) -> None: ...
    def apply_buy_in_funds_held(self, state: _buy_in.BuyInState, event: _buy_in.BuyInFundsHeld, ctx: _az.PageContext) -> None: ...
    def apply_buy_in_seated(self, state: _buy_in.BuyInState, event: _buy_in.BuyInSeated, ctx: _az.PageContext) -> None: ...
    def apply_buy_in_completed(self, state: _buy_in.BuyInState, event: _buy_in.BuyInCompleted, ctx: _az.PageContext) -> None: ...
    def apply_buy_in_failed(self, state: _buy_in.BuyInState, event: _buy_in.BuyInFailed, ctx: _az.PageContext) -> None: ...
    def on_hold_funds_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _buy_in.BuyInState) -> Optional[_pm.ProcessManagerHandleResponse]: ...
    def on_confirm_seat_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _buy_in.BuyInState) -> Optional[_pm.ProcessManagerHandleResponse]: ...

def new_buy_in_process_manager_dispatch(handler: BuyInProcessManagerHandler) -> _az.ProcessManagerDispatch:
    rebuilder = _az.Rebuilder(lambda: _buy_in.BuyInState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_buy_in_started(state, payload, ctx):
        event = _buy_in.BuyInStarted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_started(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BuyInStarted", _apply_apply_buy_in_started)
    def _apply_apply_buy_in_funds_held(state, payload, ctx):
        event = _buy_in.BuyInFundsHeld()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_funds_held(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BuyInFundsHeld", _apply_apply_buy_in_funds_held)
    def _apply_apply_buy_in_seated(state, payload, ctx):
        event = _buy_in.BuyInSeated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_seated(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BuyInSeated", _apply_apply_buy_in_seated)
    def _apply_apply_buy_in_completed(state, payload, ctx):
        event = _buy_in.BuyInCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_completed(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BuyInCompleted", _apply_apply_buy_in_completed)
    def _apply_apply_buy_in_failed(state, payload, ctx):
        event = _buy_in.BuyInFailed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_failed(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BuyInFailed", _apply_apply_buy_in_failed)
    dispatch = _az.ProcessManagerDispatch("BuyInProcessManager", "buy-in", rebuilder, targets=["player", "table"])
    def _on_funds_held(event_any, state, dests, trigger_cover):
        event = _player.FundsHeld()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.funds_held(event, state, dests, trigger_cover)
    dispatch.on_event_with_cover("player", "io.angzarr.examples.v1.FundsHeld", _on_funds_held)
    def _on_funds_captured(event_any, state, dests, trigger_cover):
        event = _player.FundsCaptured()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.funds_captured(event, state, dests, trigger_cover)
    dispatch.on_event_with_cover("player", "io.angzarr.examples.v1.FundsCaptured", _on_funds_captured)
    def _on_seat_held(event_any, state, dests, trigger_cover):
        event = _table.SeatHeld()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.seat_held(event, state, dests, trigger_cover)
    dispatch.on_event_with_cover("table", "io.angzarr.examples.v1.SeatHeld", _on_seat_held)
    def _on_player_seated(event_any, state, dests, trigger_cover):
        event = _table.PlayerSeated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.player_seated(event, state, dests, trigger_cover)
    dispatch.on_event_with_cover("table", "io.angzarr.examples.v1.PlayerSeated", _on_player_seated)
    dispatch.on_rejected("io.angzarr.examples.v1.HoldFunds", handler.on_hold_funds_rejected)
    dispatch.on_rejected("io.angzarr.examples.v1.ConfirmSeat", handler.on_confirm_seat_rejected)
    return dispatch

def register_buy_in_process_manager(router: _az.Router, handler: BuyInProcessManagerHandler) -> None:
    router.register_process_manager(new_buy_in_process_manager_dispatch(handler))

