# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/ledger.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import ledger_pb2 as _ledger
from . import player_pb2 as _player
from . import table_pb2 as _table

class LedgerProjectorHandler(Protocol):
    """Strict business seam for the LedgerProjector projector."""

    def player_registered(self, projection: _ledger.LedgerProjection, event: _player.PlayerRegistered, ctx: _az.PageContext) -> None: ...
    def player_imported(self, projection: _ledger.LedgerProjection, event: _player.PlayerImported, ctx: _az.PageContext) -> None: ...
    def profile_updated(self, projection: _ledger.LedgerProjection, event: _player.ProfileUpdated, ctx: _az.PageContext) -> None: ...
    def funds_deposited(self, projection: _ledger.LedgerProjection, event: _player.FundsDeposited, ctx: _az.PageContext) -> None: ...
    def funds_withdrawn(self, projection: _ledger.LedgerProjection, event: _player.FundsWithdrawn, ctx: _az.PageContext) -> None: ...
    def funds_held(self, projection: _ledger.LedgerProjection, event: _player.FundsHeld, ctx: _az.PageContext) -> None: ...
    def funds_captured(self, projection: _ledger.LedgerProjection, event: _player.FundsCaptured, ctx: _az.PageContext) -> None: ...
    def hold_released(self, projection: _ledger.LedgerProjection, event: _player.HoldReleased, ctx: _az.PageContext) -> None: ...
    def top_up_requested(self, projection: _ledger.LedgerProjection, event: _player.TopUpRequested, ctx: _az.PageContext) -> None: ...
    def top_up_refused(self, projection: _ledger.LedgerProjection, event: _player.TopUpRefused, ctx: _az.PageContext) -> None: ...
    def top_up_settled(self, projection: _ledger.LedgerProjection, event: _player.TopUpSettled, ctx: _az.PageContext) -> None: ...
    def cash_out_credited(self, projection: _ledger.LedgerProjection, event: _player.CashOutCredited, ctx: _az.PageContext) -> None: ...
    def loyalty_enrolled(self, projection: _ledger.LedgerProjection, event: _player.LoyaltyEnrolled, ctx: _az.PageContext) -> None: ...
    def round_result_recorded(self, projection: _ledger.LedgerProjection, event: _player.RoundResultRecorded, ctx: _az.PageContext) -> None: ...
    def round_result_retracted(self, projection: _ledger.LedgerProjection, event: _player.RoundResultRetracted, ctx: _az.PageContext) -> None: ...
    def loyalty_points_awarded(self, projection: _ledger.LedgerProjection, event: _player.LoyaltyPointsAwarded, ctx: _az.PageContext) -> None: ...
    def table_created(self, projection: _ledger.LedgerProjection, event: _table.TableCreated, ctx: _az.PageContext) -> None: ...
    def player_seated(self, projection: _ledger.LedgerProjection, event: _table.PlayerSeated, ctx: _az.PageContext) -> None: ...
    def chips_added(self, projection: _ledger.LedgerProjection, event: _table.ChipsAdded, ctx: _az.PageContext) -> None: ...
    def player_cashed_out(self, projection: _ledger.LedgerProjection, event: _table.PlayerCashedOut, ctx: _az.PageContext) -> None: ...
    def bet_placed(self, projection: _ledger.LedgerProjection, event: _table.BetPlaced, ctx: _az.PageContext) -> None: ...
    def hand_doubled(self, projection: _ledger.LedgerProjection, event: _table.HandDoubled, ctx: _az.PageContext) -> None: ...
    def round_settled(self, projection: _ledger.LedgerProjection, event: _table.RoundSettled, ctx: _az.PageContext) -> None: ...
    def finish(self, projection: _ledger.LedgerProjection, events: _t.EventBook) -> _t.Projection: ...

def new_ledger_projector_dispatch(handler: LedgerProjectorHandler) -> _az.ProjectorDispatch:
    dispatch = _az.ProjectorDispatch("LedgerProjector", lambda: _ledger.LedgerProjection())
    dispatch.for_domains("player", "table")
    def _on_player_registered(projection, event_any, ctx):
        event = _player.PlayerRegistered()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.player_registered(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.PlayerRegistered", _on_player_registered)
    def _on_player_imported(projection, event_any, ctx):
        event = _player.PlayerImported()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.player_imported(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.PlayerImported", _on_player_imported)
    def _on_profile_updated(projection, event_any, ctx):
        event = _player.ProfileUpdated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.profile_updated(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.ProfileUpdated", _on_profile_updated)
    def _on_funds_deposited(projection, event_any, ctx):
        event = _player.FundsDeposited()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.funds_deposited(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.FundsDeposited", _on_funds_deposited)
    def _on_funds_withdrawn(projection, event_any, ctx):
        event = _player.FundsWithdrawn()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.funds_withdrawn(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.FundsWithdrawn", _on_funds_withdrawn)
    def _on_funds_held(projection, event_any, ctx):
        event = _player.FundsHeld()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.funds_held(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.FundsHeld", _on_funds_held)
    def _on_funds_captured(projection, event_any, ctx):
        event = _player.FundsCaptured()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.funds_captured(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.FundsCaptured", _on_funds_captured)
    def _on_hold_released(projection, event_any, ctx):
        event = _player.HoldReleased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.hold_released(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.HoldReleased", _on_hold_released)
    def _on_top_up_requested(projection, event_any, ctx):
        event = _player.TopUpRequested()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.top_up_requested(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.TopUpRequested", _on_top_up_requested)
    def _on_top_up_refused(projection, event_any, ctx):
        event = _player.TopUpRefused()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.top_up_refused(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.TopUpRefused", _on_top_up_refused)
    def _on_top_up_settled(projection, event_any, ctx):
        event = _player.TopUpSettled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.top_up_settled(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.TopUpSettled", _on_top_up_settled)
    def _on_cash_out_credited(projection, event_any, ctx):
        event = _player.CashOutCredited()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.cash_out_credited(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.CashOutCredited", _on_cash_out_credited)
    def _on_loyalty_enrolled(projection, event_any, ctx):
        event = _player.LoyaltyEnrolled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.loyalty_enrolled(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.LoyaltyEnrolled", _on_loyalty_enrolled)
    def _on_round_result_recorded(projection, event_any, ctx):
        event = _player.RoundResultRecorded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.round_result_recorded(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.RoundResultRecorded", _on_round_result_recorded)
    def _on_round_result_retracted(projection, event_any, ctx):
        event = _player.RoundResultRetracted()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.round_result_retracted(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.RoundResultRetracted", _on_round_result_retracted)
    def _on_loyalty_points_awarded(projection, event_any, ctx):
        event = _player.LoyaltyPointsAwarded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.loyalty_points_awarded(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.LoyaltyPointsAwarded", _on_loyalty_points_awarded)
    def _on_table_created(projection, event_any, ctx):
        event = _table.TableCreated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.table_created(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.TableCreated", _on_table_created)
    def _on_player_seated(projection, event_any, ctx):
        event = _table.PlayerSeated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.player_seated(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.PlayerSeated", _on_player_seated)
    def _on_chips_added(projection, event_any, ctx):
        event = _table.ChipsAdded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.chips_added(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.ChipsAdded", _on_chips_added)
    def _on_player_cashed_out(projection, event_any, ctx):
        event = _table.PlayerCashedOut()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.player_cashed_out(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.PlayerCashedOut", _on_player_cashed_out)
    def _on_bet_placed(projection, event_any, ctx):
        event = _table.BetPlaced()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.bet_placed(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.BetPlaced", _on_bet_placed)
    def _on_hand_doubled(projection, event_any, ctx):
        event = _table.HandDoubled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.hand_doubled(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.HandDoubled", _on_hand_doubled)
    def _on_round_settled(projection, event_any, ctx):
        event = _table.RoundSettled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.round_settled(projection, event, ctx)
    dispatch.on_event_with_context("io.angzarr.examples.v1.RoundSettled", _on_round_settled)
    dispatch.finish(handler.finish)
    return dispatch

def register_ledger_projector(router: _az.Router, handler: LedgerProjectorHandler) -> None:
    router.register_projector(new_ledger_projector_dispatch(handler))

