# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/player.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from angzarr_client.proto.io.angzarr.v1 import command_handler_pb2 as _ch
from . import player_pb2 as _player

class PlayerAggregateHandler(Protocol):
    """Strict business seam for the PlayerAggregate aggregate."""

    def register_player(self, cmd: _player.RegisterPlayer, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def import_player(self, cmd: _player.ImportPlayer, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def update_profile(self, cmd: _player.UpdateProfile, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def deposit_funds(self, cmd: _player.DepositFunds, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def withdraw_funds(self, cmd: _player.WithdrawFunds, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def request_top_up(self, cmd: _player.RequestTopUp, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def enroll_loyalty(self, cmd: _player.EnrollLoyalty, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def hold_funds(self, cmd: _player.HoldFunds, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def capture_funds(self, cmd: _player.CaptureFunds, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_hold(self, cmd: _player.ReleaseHold, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def record_round_result(self, cmd: _player.RecordRoundResult, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def award_loyalty_points(self, cmd: _player.AwardLoyaltyPoints, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_player_registered(self, state: _player.PlayerState, event: _player.PlayerRegistered, ctx: _az.PageContext) -> None: ...
    def apply_player_imported(self, state: _player.PlayerState, event: _player.PlayerImported, ctx: _az.PageContext) -> None: ...
    def apply_profile_updated(self, state: _player.PlayerState, event: _player.ProfileUpdated, ctx: _az.PageContext) -> None: ...
    def apply_funds_deposited(self, state: _player.PlayerState, event: _player.FundsDeposited, ctx: _az.PageContext) -> None: ...
    def apply_funds_withdrawn(self, state: _player.PlayerState, event: _player.FundsWithdrawn, ctx: _az.PageContext) -> None: ...
    def apply_funds_held(self, state: _player.PlayerState, event: _player.FundsHeld, ctx: _az.PageContext) -> None: ...
    def apply_funds_captured(self, state: _player.PlayerState, event: _player.FundsCaptured, ctx: _az.PageContext) -> None: ...
    def apply_hold_released(self, state: _player.PlayerState, event: _player.HoldReleased, ctx: _az.PageContext) -> None: ...
    def apply_top_up_requested(self, state: _player.PlayerState, event: _player.TopUpRequested, ctx: _az.PageContext) -> None: ...
    def apply_top_up_refused(self, state: _player.PlayerState, event: _player.TopUpRefused, ctx: _az.PageContext) -> None: ...
    def apply_top_up_settled(self, state: _player.PlayerState, event: _player.TopUpSettled, ctx: _az.PageContext) -> None: ...
    def apply_cash_out_credited(self, state: _player.PlayerState, event: _player.CashOutCredited, ctx: _az.PageContext) -> None: ...
    def apply_loyalty_enrolled(self, state: _player.PlayerState, event: _player.LoyaltyEnrolled, ctx: _az.PageContext) -> None: ...
    def apply_round_result_recorded(self, state: _player.PlayerState, event: _player.RoundResultRecorded, ctx: _az.PageContext) -> None: ...
    def apply_round_result_retracted(self, state: _player.PlayerState, event: _player.RoundResultRetracted, ctx: _az.PageContext) -> None: ...
    def apply_loyalty_points_awarded(self, state: _player.PlayerState, event: _player.LoyaltyPointsAwarded, ctx: _az.PageContext) -> None: ...
    def on_add_chips_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_ch.BusinessResponse]: ...
    def on_top_up_settled_fact(self, fact: _player.TopUpSettled, state: _player.PlayerState) -> Optional[_az.FactRecord]: ...
    def on_cash_out_credited_fact(self, fact: _player.CashOutCredited, state: _player.PlayerState) -> Optional[_az.FactRecord]: ...
    def on_record_round_result_undo(self, n: _t.Notification, compensate: _t.Compensate, state: _player.PlayerState, cctx: _az.CommandContext) -> Optional[_ch.BusinessResponse]: ...

def new_player_aggregate_dispatch(handler: PlayerAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _player.PlayerState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_player_registered(state, payload, ctx):
        event = _player.PlayerRegistered()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_registered(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.PlayerRegistered", _apply_apply_player_registered)
    def _apply_apply_player_imported(state, payload, ctx):
        event = _player.PlayerImported()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_imported(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.PlayerImported", _apply_apply_player_imported)
    def _apply_apply_profile_updated(state, payload, ctx):
        event = _player.ProfileUpdated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_profile_updated(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.ProfileUpdated", _apply_apply_profile_updated)
    def _apply_apply_funds_deposited(state, payload, ctx):
        event = _player.FundsDeposited()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_deposited(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.FundsDeposited", _apply_apply_funds_deposited)
    def _apply_apply_funds_withdrawn(state, payload, ctx):
        event = _player.FundsWithdrawn()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_withdrawn(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.FundsWithdrawn", _apply_apply_funds_withdrawn)
    def _apply_apply_funds_held(state, payload, ctx):
        event = _player.FundsHeld()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_held(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.FundsHeld", _apply_apply_funds_held)
    def _apply_apply_funds_captured(state, payload, ctx):
        event = _player.FundsCaptured()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_captured(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.FundsCaptured", _apply_apply_funds_captured)
    def _apply_apply_hold_released(state, payload, ctx):
        event = _player.HoldReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hold_released(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.HoldReleased", _apply_apply_hold_released)
    def _apply_apply_top_up_requested(state, payload, ctx):
        event = _player.TopUpRequested()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_top_up_requested(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.TopUpRequested", _apply_apply_top_up_requested)
    def _apply_apply_top_up_refused(state, payload, ctx):
        event = _player.TopUpRefused()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_top_up_refused(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.TopUpRefused", _apply_apply_top_up_refused)
    def _apply_apply_top_up_settled(state, payload, ctx):
        event = _player.TopUpSettled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_top_up_settled(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.TopUpSettled", _apply_apply_top_up_settled)
    def _apply_apply_cash_out_credited(state, payload, ctx):
        event = _player.CashOutCredited()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_cash_out_credited(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.CashOutCredited", _apply_apply_cash_out_credited)
    def _apply_apply_loyalty_enrolled(state, payload, ctx):
        event = _player.LoyaltyEnrolled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_loyalty_enrolled(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.LoyaltyEnrolled", _apply_apply_loyalty_enrolled)
    def _apply_apply_round_result_recorded(state, payload, ctx):
        event = _player.RoundResultRecorded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_round_result_recorded(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.RoundResultRecorded", _apply_apply_round_result_recorded)
    def _apply_apply_round_result_retracted(state, payload, ctx):
        event = _player.RoundResultRetracted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_round_result_retracted(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.RoundResultRetracted", _apply_apply_round_result_retracted)
    def _apply_apply_loyalty_points_awarded(state, payload, ctx):
        event = _player.LoyaltyPointsAwarded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_loyalty_points_awarded(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.LoyaltyPointsAwarded", _apply_apply_loyalty_points_awarded)
    dispatch = _az.AggregateDispatch("PlayerAggregate", "player", rebuilder)
    def _on_register_player(cmd_any, state, cctx):
        cmd = _player.RegisterPlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.register_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RegisterPlayer", _on_register_player)
    def _on_import_player(cmd_any, state, cctx):
        cmd = _player.ImportPlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.import_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ImportPlayer", _on_import_player)
    def _on_update_profile(cmd_any, state, cctx):
        cmd = _player.UpdateProfile()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.update_profile(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.UpdateProfile", _on_update_profile)
    def _on_deposit_funds(cmd_any, state, cctx):
        cmd = _player.DepositFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deposit_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DepositFunds", _on_deposit_funds)
    def _on_withdraw_funds(cmd_any, state, cctx):
        cmd = _player.WithdrawFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.withdraw_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.WithdrawFunds", _on_withdraw_funds)
    def _on_request_top_up(cmd_any, state, cctx):
        cmd = _player.RequestTopUp()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.request_top_up(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RequestTopUp", _on_request_top_up)
    def _on_enroll_loyalty(cmd_any, state, cctx):
        cmd = _player.EnrollLoyalty()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.enroll_loyalty(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.EnrollLoyalty", _on_enroll_loyalty)
    def _on_hold_funds(cmd_any, state, cctx):
        cmd = _player.HoldFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.hold_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.HoldFunds", _on_hold_funds)
    def _on_capture_funds(cmd_any, state, cctx):
        cmd = _player.CaptureFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.capture_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CaptureFunds", _on_capture_funds)
    def _on_release_hold(cmd_any, state, cctx):
        cmd = _player.ReleaseHold()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_hold(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseHold", _on_release_hold)
    def _on_record_round_result(cmd_any, state, cctx):
        cmd = _player.RecordRoundResult()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.record_round_result(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RecordRoundResult", _on_record_round_result)
    def _on_award_loyalty_points(cmd_any, state, cctx):
        cmd = _player.AwardLoyaltyPoints()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.award_loyalty_points(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.AwardLoyaltyPoints", _on_award_loyalty_points)
    dispatch.on_rejected("io.angzarr.examples.v1.AddChips", handler.on_add_chips_rejected)
    def _fact_on_top_up_settled_fact(fact_any, state):
        fact = _player.TopUpSettled()
        try:
            fact.ParseFromString(fact_any.value)
        except Exception as exc:
            raise _az.any_decode_error(fact_any.type_url, exc)
        rec = handler.on_top_up_settled_fact(fact, state)
        return rec if rec is not None else _az.FactRecord.as_received(fact_any)
    dispatch.on_fact("io.angzarr.examples.v1.TopUpSettled", _fact_on_top_up_settled_fact)
    def _fact_on_cash_out_credited_fact(fact_any, state):
        fact = _player.CashOutCredited()
        try:
            fact.ParseFromString(fact_any.value)
        except Exception as exc:
            raise _az.any_decode_error(fact_any.type_url, exc)
        rec = handler.on_cash_out_credited_fact(fact, state)
        return rec if rec is not None else _az.FactRecord.as_received(fact_any)
    dispatch.on_fact("io.angzarr.examples.v1.CashOutCredited", _fact_on_cash_out_credited_fact)
    dispatch.on_undo("io.angzarr.examples.v1.RecordRoundResult", handler.on_record_round_result_undo)
    return dispatch

def register_player_aggregate(router: _az.Router, handler: PlayerAggregateHandler) -> None:
    router.register_aggregate(new_player_aggregate_dispatch(handler))

