# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/sagas.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import player_pb2 as _player

class PlayerTableSagaHandler(Protocol):
    """Strict business seam for the PlayerTableSaga saga."""

    def top_up_requested(self, event: _player.TopUpRequested, dests: _az.Destinations, source: _az.PageContext) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_player_table_saga_dispatch(handler: PlayerTableSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("PlayerTableSaga", "player", targets=["table"])
    def _on_top_up_requested(event_any, dests, source):
        event = _player.TopUpRequested()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.top_up_requested(event, dests, source)
    dispatch.on_event_with_context("io.angzarr.examples.v1.TopUpRequested", _on_top_up_requested)
    return dispatch

def register_player_table_saga(router: _az.Router, handler: PlayerTableSagaHandler) -> None:
    router.register_saga(new_player_table_saga_dispatch(handler))

