# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/sagas.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import table_pb2 as _table

class TablePlayerHistorySagaHandler(Protocol):
    """Strict business seam for the TablePlayerHistorySaga saga."""

    def round_settled(self, event: _table.RoundSettled, dests: _az.Destinations, source: _az.PageContext) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_table_player_history_saga_dispatch(handler: TablePlayerHistorySagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("TablePlayerHistorySaga", "table", targets=["player"])
    def _on_round_settled(event_any, dests, source):
        event = _table.RoundSettled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.round_settled(event, dests, source)
    dispatch.on_event_with_context("io.angzarr.examples.v1.RoundSettled", _on_round_settled)
    return dispatch

def register_table_player_history_saga(router: _az.Router, handler: TablePlayerHistorySagaHandler) -> None:
    router.register_saga(new_table_player_history_saga_dispatch(handler))

