# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/table.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import table_pb2 as _table

class TableAggregateHandler(Protocol):
    """Strict business seam for the TableAggregate aggregate."""

    def create_table(self, cmd: _table.CreateTable, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def request_seat(self, cmd: _table.RequestSeat, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def leave_table(self, cmd: _table.LeaveTable, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def place_bet(self, cmd: _table.PlaceBet, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def deal_round(self, cmd: _table.DealRound, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def hit(self, cmd: _table.Hit, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def stand(self, cmd: _table.Stand, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def double_down(self, cmd: _table.DoubleDown, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def confirm_seat(self, cmd: _table.ConfirmSeat, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_seat(self, cmd: _table.ReleaseSeat, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def add_chips(self, cmd: _table.AddChips, state: _table.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_table_created(self, state: _table.TableState, event: _table.TableCreated, ctx: _az.PageContext) -> None: ...
    def apply_shoe_shuffled(self, state: _table.TableState, event: _table.ShoeShuffled, ctx: _az.PageContext) -> None: ...
    def apply_seat_held(self, state: _table.TableState, event: _table.SeatHeld, ctx: _az.PageContext) -> None: ...
    def apply_seat_released(self, state: _table.TableState, event: _table.SeatReleased, ctx: _az.PageContext) -> None: ...
    def apply_player_seated(self, state: _table.TableState, event: _table.PlayerSeated, ctx: _az.PageContext) -> None: ...
    def apply_chips_added(self, state: _table.TableState, event: _table.ChipsAdded, ctx: _az.PageContext) -> None: ...
    def apply_player_cashed_out(self, state: _table.TableState, event: _table.PlayerCashedOut, ctx: _az.PageContext) -> None: ...
    def apply_bet_placed(self, state: _table.TableState, event: _table.BetPlaced, ctx: _az.PageContext) -> None: ...
    def apply_round_dealt(self, state: _table.TableState, event: _table.RoundDealt, ctx: _az.PageContext) -> None: ...
    def apply_card_dealt(self, state: _table.TableState, event: _table.CardDealt, ctx: _az.PageContext) -> None: ...
    def apply_hand_stood(self, state: _table.TableState, event: _table.HandStood, ctx: _az.PageContext) -> None: ...
    def apply_hand_doubled(self, state: _table.TableState, event: _table.HandDoubled, ctx: _az.PageContext) -> None: ...
    def apply_dealer_played(self, state: _table.TableState, event: _table.DealerPlayed, ctx: _az.PageContext) -> None: ...
    def apply_round_settled(self, state: _table.TableState, event: _table.RoundSettled, ctx: _az.PageContext) -> None: ...

def new_table_aggregate_dispatch(handler: TableAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _table.TableState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_table_created(state, payload, ctx):
        event = _table.TableCreated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_table_created(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.TableCreated", _apply_apply_table_created)
    def _apply_apply_shoe_shuffled(state, payload, ctx):
        event = _table.ShoeShuffled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_shoe_shuffled(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.ShoeShuffled", _apply_apply_shoe_shuffled)
    def _apply_apply_seat_held(state, payload, ctx):
        event = _table.SeatHeld()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_seat_held(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.SeatHeld", _apply_apply_seat_held)
    def _apply_apply_seat_released(state, payload, ctx):
        event = _table.SeatReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_seat_released(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.SeatReleased", _apply_apply_seat_released)
    def _apply_apply_player_seated(state, payload, ctx):
        event = _table.PlayerSeated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_seated(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.PlayerSeated", _apply_apply_player_seated)
    def _apply_apply_chips_added(state, payload, ctx):
        event = _table.ChipsAdded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_chips_added(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.ChipsAdded", _apply_apply_chips_added)
    def _apply_apply_player_cashed_out(state, payload, ctx):
        event = _table.PlayerCashedOut()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_cashed_out(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.PlayerCashedOut", _apply_apply_player_cashed_out)
    def _apply_apply_bet_placed(state, payload, ctx):
        event = _table.BetPlaced()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_bet_placed(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.BetPlaced", _apply_apply_bet_placed)
    def _apply_apply_round_dealt(state, payload, ctx):
        event = _table.RoundDealt()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_round_dealt(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.RoundDealt", _apply_apply_round_dealt)
    def _apply_apply_card_dealt(state, payload, ctx):
        event = _table.CardDealt()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_card_dealt(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.CardDealt", _apply_apply_card_dealt)
    def _apply_apply_hand_stood(state, payload, ctx):
        event = _table.HandStood()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hand_stood(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.HandStood", _apply_apply_hand_stood)
    def _apply_apply_hand_doubled(state, payload, ctx):
        event = _table.HandDoubled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hand_doubled(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.HandDoubled", _apply_apply_hand_doubled)
    def _apply_apply_dealer_played(state, payload, ctx):
        event = _table.DealerPlayed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_dealer_played(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.DealerPlayed", _apply_apply_dealer_played)
    def _apply_apply_round_settled(state, payload, ctx):
        event = _table.RoundSettled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_round_settled(state, event, ctx)
    rebuilder.apply_with_context("io.angzarr.examples.v1.RoundSettled", _apply_apply_round_settled)
    dispatch = _az.AggregateDispatch("TableAggregate", "table", rebuilder)
    def _on_create_table(cmd_any, state, cctx):
        cmd = _table.CreateTable()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.create_table(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CreateTable", _on_create_table)
    def _on_request_seat(cmd_any, state, cctx):
        cmd = _table.RequestSeat()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.request_seat(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RequestSeat", _on_request_seat)
    def _on_leave_table(cmd_any, state, cctx):
        cmd = _table.LeaveTable()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.leave_table(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.LeaveTable", _on_leave_table)
    def _on_place_bet(cmd_any, state, cctx):
        cmd = _table.PlaceBet()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.place_bet(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.PlaceBet", _on_place_bet)
    def _on_deal_round(cmd_any, state, cctx):
        cmd = _table.DealRound()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deal_round(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DealRound", _on_deal_round)
    def _on_hit(cmd_any, state, cctx):
        cmd = _table.Hit()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.hit(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.Hit", _on_hit)
    def _on_stand(cmd_any, state, cctx):
        cmd = _table.Stand()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.stand(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.Stand", _on_stand)
    def _on_double_down(cmd_any, state, cctx):
        cmd = _table.DoubleDown()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.double_down(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DoubleDown", _on_double_down)
    def _on_confirm_seat(cmd_any, state, cctx):
        cmd = _table.ConfirmSeat()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.confirm_seat(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ConfirmSeat", _on_confirm_seat)
    def _on_release_seat(cmd_any, state, cctx):
        cmd = _table.ReleaseSeat()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_seat(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseSeat", _on_release_seat)
    def _on_add_chips(cmd_any, state, cctx):
        cmd = _table.AddChips()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.add_chips(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.AddChips", _on_add_chips)
    return dispatch

def register_table_aggregate(router: _az.Router, handler: TableAggregateHandler) -> None:
    router.register_aggregate(new_table_aggregate_dispatch(handler))

