# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/sagas.proto

from typing import Optional, Protocol

import angzarr_client.router as _az
from angzarr_client.proto.io.angzarr.v1 import types_pb2 as _t
from . import table_pb2 as _table

class TablePlayerSettlementSagaHandler(Protocol):
    """Strict business seam for the TablePlayerSettlementSaga saga."""

    def chips_added(self, event: _table.ChipsAdded, dests: _az.Destinations, source: _az.PageContext) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...
    def player_cashed_out(self, event: _table.PlayerCashedOut, dests: _az.Destinations, source: _az.PageContext) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_table_player_settlement_saga_dispatch(handler: TablePlayerSettlementSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("TablePlayerSettlementSaga", "table", targets=["player"])
    def _on_chips_added(event_any, dests, source):
        event = _table.ChipsAdded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.chips_added(event, dests, source)
    dispatch.on_event_with_context("io.angzarr.examples.v1.ChipsAdded", _on_chips_added)
    def _on_player_cashed_out(event_any, dests, source):
        event = _table.PlayerCashedOut()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.player_cashed_out(event, dests, source)
    dispatch.on_event_with_context("io.angzarr.examples.v1.PlayerCashedOut", _on_player_cashed_out)
    return dispatch

def register_table_player_settlement_saga(router: _az.Router, handler: TablePlayerSettlementSagaHandler) -> None:
    router.register_saga(new_table_player_settlement_saga_dispatch(handler))

